/*
 * File: app/view/CiclosEscolaresTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.CiclosEscolaresTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.CiclosEscolaresTab',

    requires: [
        'cartera.view.InstitucionesTabViewModel1',
        'cartera.view.InstitucionesTabViewController1',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date'
    ],

    controller: 'ciclosescolarestab',
    viewModel: {
        type: 'ciclosescolarestab'
    },
    height: 630,
    id: 'CiclosEscolaresTab',
    itemId: 'CiclosEscolaresTab',
    width: 829,
    layout: 'fit',
    closable: true,
    title: 'Ciclos Escolares',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    disabled: true,
                    height: 45,
                    id: 'btnAgregarCiclo',
                    itemId: 'btnAgregarCiclo',
                    width: 45,
                    icon: 'resources/images/agregar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnAgregarInsClick'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    height: 45,
                    id: 'btnBorrarCiclo',
                    itemId: 'btnBorrarCiclo',
                    width: 45,
                    icon: 'resources/images/eliminar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnBorrarCicloClick'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    height: 45,
                    id: 'btnModificarCiclo',
                    itemId: 'btnModificarCiclo',
                    width: 45,
                    icon: 'resources/images/modificar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnModificarCicloClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnActualizarCiclo',
                    itemId: 'btnActualizarCiclo',
                    width: 45,
                    icon: 'resources/images/actualizar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnActualizarInsClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'GridCiclosEscolares',
            store: 'CiclosEscolaresStore',
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id_ciclo_escolar',
                    menuDisabled: true,
                    text: 'id_ciclo_escolar',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id_institucion',
                    menuDisabled: true,
                    text: 'id_institucion',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'ciclo',
                    text: 'Ciclo Escolar'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Fecha',
                    columns: [
                        {
                            xtype: 'datecolumn',
                            width: 180,
                            dataIndex: 'fechai',
                            menuDisabled: true,
                            text: 'Inicial',
                            format: 'F d, Y'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 180,
                            dataIndex: 'fechaf',
                            menuDisabled: true,
                            text: 'Final',
                            format: 'F d, Y'
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'estatus_des',
                    menuDisabled: true,
                    text: 'Estatus'
                }
            ],
            listeners: {
                afterrender: 'onGridcolumnAfterRender'
            }
        }
    ]

});