/*
 * File: app/view/EstatusIngresoWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.EstatusIngresoWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.estatusingresoswin',

    requires: [
        'cartera.view.InstitucionesWinViewModel6',
        'cartera.view.InstitucionesWinViewController6',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'estatusingresowin',
    viewModel: {
        type: 'estatusingresowin'
    },
    modal: true,
    autoShow: true,
    height: 186,
    id: 'FormasPagoWin1',
    itemId: 'FormasPagoWin',
    resizable: false,
    width: 377,
    title: 'Agregar Estatus Ingreso',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            height: 145,
            id: 'formEstatusIngreso',
            itemId: 'formEstatusIngreso',
            width: 881,
            layout: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_estatus_ingresoEI',
                    fieldLabel: 'id_estatus_ingreso',
                    name: 'id_estatus_ingreso',
                    hideTrigger: true
                },
                {
                    xtype: 'textfield',
                    id: 'descripcionEI',
                    fieldLabel: 'Descripción',
                    name: 'descripcion',
                    allowBlank: false,
                    validateBlank: true,
                    listeners: {
                        change: 'onDescripcionEIChange'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 84,
                    width: 843,
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            dock: 'left'
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnGuardarEI',
                            width: 100,
                            icon: 'resources/images/guardar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Guardar',
                            listeners: {
                                click: 'onbtnGuardarEI'
                            }
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnCancelarEI',
                            width: 100,
                            icon: 'resources/images/cancelar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Cancelar',
                            listeners: {
                                click: 'onbtnCancelarEI'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onFormasPagoWinAfterRender'
    }

});