/*
 * File: app/view/InstitucionesWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.InstitucionesWin',

    requires: [
        'cartera.view.InstitucionesWinViewModel',
        'cartera.view.InstitucionesWinViewController',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.Img',
        'Ext.form.field.Number',
        'Ext.form.field.File',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'institucioneswin1',
    viewModel: {
        type: 'InstitucionesWin'
    },
    modal: true,
    autoShow: true,
    height: 546,
    id: 'winGen1',
    itemId: 'winGen',
    resizable: false,
    width: 849,
    title: 'Agregar Institución',

    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            height: 180,
            id: 'comboForm',
            itemId: 'comboForm',
            width: 457,
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'fieldset',
                    dock: 'left',
                    height: 104,
                    width: 409,
                    layout: 'form',
                    title: 'Institución',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'institucionescmb',
                            name: 'id_institucion',
                            editable: false,
                            displayField: 'nombre',
                            store: 'InstitucionesStore',
                            valueField: 'id_institucion',
                            listeners: {
                                change: 'onInstitucionescmbChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    dock: 'left',
                    height: 104,
                    width: 438,
                    title: 'Logo',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'image',
                            height: 120,
                            id: 'imglogo',
                            width: 120,
                            imgCls: ''
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            height: 331,
            id: 'institucionesForm',
            itemId: 'institucionesForm',
            width: 843,
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'fieldset',
                    dock: 'left',
                    height: 439,
                    width: 419,
                    layout: 'form',
                    title: 'Datos Fiscales',
                    items: [
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'id_institucion_dato',
                            fieldLabel: 'id_institucion_dato',
                            name: 'id_institucion_dato',
                            hideTrigger: true
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'id_institucion',
                            fieldLabel: 'id_institucion',
                            name: 'id_institucion',
                            hideTrigger: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'rfc',
                            fieldLabel: 'R.F.C',
                            name: 'rfc',
                            allowBlank: false,
                            maxLength: 13,
                            maxLengthText: 'RFC inválido',
                            validateBlank: true,
                            listeners: {
                                change: 'onRfcChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            id: 'calle',
                            fieldLabel: 'Calle',
                            name: 'calle',
                            allowBlank: false,
                            validateBlank: true,
                            listeners: {
                                change: 'onCalleChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            id: 'colonia',
                            fieldLabel: 'Colonia',
                            name: 'colonia',
                            allowBlank: false,
                            validateBlank: true,
                            listeners: {
                                change: 'onColoniaChange'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            alignOnScroll: false,
                            id: 'codigo_postal',
                            fieldLabel: 'Código Postal',
                            name: 'codigo_postal',
                            allowBlank: false,
                            hideTrigger: true,
                            maxLength: 5,
                            maxLengthText: 'Máximo 5 caracteres',
                            validateBlank: true,
                            spinDownEnabled: false,
                            spinUpEnabled: false,
                            allowDecimals: false,
                            allowExponential: false,
                            maxText: 'Máximo 5 caracteres'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    dock: 'right',
                    height: 353,
                    width: 430,
                    layout: 'form',
                    title: '-',
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'razon_social',
                            itemId: 'razon_social',
                            fieldLabel: 'Razón Social',
                            name: 'razon_social',
                            allowBlank: false,
                            validateBlank: true,
                            listeners: {
                                change: 'onRazon_socialChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            id: 'numero_exterior',
                            fieldLabel: 'No Exterior',
                            name: 'numero_exterior',
                            allowBlank: false,
                            validateBlank: true,
                            listeners: {
                                change: 'onNo_exteriorChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            id: 'numero_interior',
                            fieldLabel: 'No Interior',
                            name: 'numero_interior',
                            listeners: {
                                change: 'onNo_interiorChange'
                            }
                        },
                        {
                            xtype: 'filefield',
                            dock: 'top',
                            fieldLabel: 'Logo',
                            name: 'ruta_logo',
                            buttonText: 'Buscar...',
                            listeners: {
                                afterrender: 'onFilefieldAfterRender',
                                change: 'onFilefieldChange'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'txtImagen',
                            name: 'imagen',
                            value: 0
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 84,
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            dock: 'left'
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnGuardarIns',
                            width: 100,
                            icon: 'resources/images/guardar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Guardar',
                            listeners: {
                                click: 'onbtnGuardar'
                            }
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnCancelarIns',
                            width: 100,
                            icon: 'resources/images/cancelar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Cancelar',
                            listeners: {
                                click: 'onbtnCancelar'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWinGen1AfterRender'
    }

});