/*
 * File: app/view/InstitucionesTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.InstitucionesTab',

    requires: [
        'cartera.view.InstitucionesTabViewModel',
        'cartera.view.InstitucionesTabViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action'
    ],

    controller: 'institucionestab',
    viewModel: {
        type: 'institucionestab'
    },
    height: 630,
    id: 'InstitucionesTab',
    itemId: 'InstitucionesTab',
    width: 829,
    layout: 'fit',
    closable: true,
    title: 'Instituciones',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnAgregarIns',
                    itemId: 'btnAgregarIns',
                    width: 45,
                    icon: 'resources/images/agregar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnAgregarInsClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnBorrarIns',
                    itemId: 'btnBorrarIns',
                    width: 45,
                    icon: 'resources/images/eliminar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnBorrarInsClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnModificarIns',
                    itemId: 'btnModificarIns',
                    width: 45,
                    icon: 'resources/images/modificar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnModificarInsClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnActualizarIns',
                    itemId: 'btnActualizarIns',
                    width: 45,
                    icon: 'resources/images/actualizar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnActualizarInsClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'GridInstituciones',
            store: 'DatosStore',
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id_institucion_dato',
                    menuDisabled: true,
                    text: 'id_institucion_dato',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id_institucion',
                    menuDisabled: true,
                    text: 'id_institucion',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'rfc',
                    menuDisabled: true,
                    text: 'R.F.C'
                },
                {
                    xtype: 'gridcolumn',
                    width: 400,
                    dataIndex: 'razon_social',
                    menuDisabled: true,
                    text: 'Razón Social'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'calle',
                    menuDisabled: true,
                    text: 'Calle'
                },
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'numero_exterior',
                    menuDisabled: true,
                    text: 'No Exterior'
                },
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'numero_interior',
                    menuDisabled: true,
                    text: 'No Interior'
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'colonia',
                    menuDisabled: true,
                    text: 'Colonia'
                },
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'codigo_postal',
                    menuDisabled: true,
                    text: 'Código Postal'
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        this.items[0].icon = record.get('logo') ==1  ? "resources/images/ok2.png" : "resources/images/eliminar.png";
                        return value;
                    },
                    align: 'center',
                    dataIndex: 'logo',
                    text: 'Logo',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {

                            }
                        }
                    ]
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        this.items[0].icon = record.get('estatus') == 1 ? "resources/images/ok2.png" : "resources/images/eliminar.png";
                        return value;
                    },
                    align: 'center',
                    dataIndex: 'estatus',
                    text: 'Estatus',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                console.log(record.data.estatus);
                                var razon_social = record.data.razon_social;
                                if(record.data.estatus === 1){
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Institución',
                                        buttons : Ext.MessageBox.YESNO,
                                        buttonText:{
                                            yes:'Sí',
                                            no:'No',
                                            cancel:'Cancelar'
                                        },
                                        msg : '¿Desea Desactivar a '+razon_social+'?',
                                        icon : Ext.Msg.WARNING,
                                        fn : function(btn)
                                        {
                                            if (btn == 'yes')
                                            {
                                                var values= {'estatus': 0};
                                                record.set(values);
                                                Ext.getStore('DatosStore').sync({
                                                    callback: function(records, operation, success)
                                                    {
                                                        Ext.MessageBox.show({
                                                            title : 'Desactivar Institución',
                                                            buttons : Ext.MessageBox.OK,
                                                            msg : 'Institución desactivada correctamente',
                                                            icon : Ext.Msg.INFO
                                                        });
                                                    }
                                                });
                                                Ext.getStore('DatosStore').load();
                                            }
                                        }
                                    });
                                }
                                else{
                                    Ext.MessageBox.show({
                                        title : 'Activar Institución',
                                        buttons : Ext.MessageBox.YESNO,
                                        buttonText:{
                                            yes:'Sí',
                                            no:'No',
                                            cancel:'Cancelar'
                                        },
                                        msg : '¿Desea Activar a '+razon_social+'?',
                                        icon : Ext.Msg.WARNING,
                                        fn : function(btn)
                                        {
                                            if (btn == 'yes')
                                            {
                                                var values= {'estatus': 1};
                                                record.set(values);
                                                Ext.getStore('DatosStore').sync({
                                                    callback: function(records, operation, success)
                                                    {
                                                        Ext.MessageBox.show({
                                                            title : 'Activar Institución',
                                                            buttons : Ext.MessageBox.OK,
                                                            msg : 'Instutición Activada correctamente',
                                                            icon : Ext.Msg.INFO
                                                        });
                                                    }
                                                });

                                                Ext.getStore('DatosStore').load();
                                            }
                                        }
                                    });
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onGridcolumnAfterRender'
            }
        }
    ]

});