/*
 * File: app/view/InstitucionesTabViewController21.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesTabViewController21', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.alumnosparcialidadtab',

    onTextfieldChange: function(field, newValue, oldValue, eOpts) {
        var busqueda = Ext.getCmp('txtBuscarAlumnoC').getValue().toUpperCase();

        if(newValue === ''){

            Ext.getStore('BusAlumnoStore').clearFilter();

        }else {
            Ext.getStore('BusAlumnoStore').clearFilter();
            Ext.getStore('BusAlumnoStore').filter({
                filterFn: function(f) {
                    return f.get('ap_paterno').indexOf(busqueda) > -1;
                }
            });
        }
    },

    onTextfieldKeypress: function(textfield, e, eOpts) {
        var busqueda = Ext.getCmp('txtBuscarAlumnoC').getValue().toUpperCase();

        if(newValue === ''){

            Ext.getStore('BusAlumnoStore').clearFilter();

        }else {
            Ext.getStore('BusAlumnoStore').clearFilter();
            Ext.getStore('BusAlumnoStore').filter({
                filterFn: function(f) {
                    return f.get('ap_paterno').indexOf(busqueda) > -1;
                }
            });
        }
    },

    onGridcolumnAfterRender: function(component, eOpts) {
        Ext.getStore('BusAlumnoStore').load({
            params:{
                'id_institucion': Ext._id_institucion
            },
        });

    },

    onGridAlumosCCellDblClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

        Ext._id_alumno=0;
        Ext.getCmp('ParcialidadesForm').getForm().reset();
        Ext.getCmp('ParcialidadesForm').getForm().reset();


        Ext.getStore('CobrosAlumnoParcialidadStore').load({
            params:{
                'matricula': record.data.matricula_nueva
            },
            callback: function(records) {
                if (records.length > 0) {
                    var datos= records[0].data;
                    Ext.getCmp('txtAlumnoPar').setValue(datos.nombre);
                    Ext.getCmp('id_alumnoPar').setValue(datos.id_alumno);
                    Ext.getCmp('txtNivelPar').setValue(datos.nivel);
                    Ext.getCmp('txtMatriculaPar').setValue(datos.matricula);
                    Ext.getCmp('txtGradoPar').setValue(datos.grado);
                    Ext.getCmp('txtGrupoPar').setValue(datos.grupo);

                    //Ext.getCmp('txtReferenciaPar').setValue(datos.referencia);
                    //Ext.getCmp('cmbTipoPar').setValue("INSCRIPC");

                    if (datos.rfc===null)
                    {
                        Ext.getCmp('cmbRFCPar').setValue('XAXX010101000');
                        Ext.getCmp('txtRazonSocialPar').setValue(Ext.getCmp('txtAlumnoPar').getValue());
                        Ext.getCmp('txtUsoCFDIPar').setValue("D10");
                        Ext.getCmp('txtIdDatoFacPar').setValue("0");

                    }else{
                        Ext.getCmp('cmbRFCPar').setValue(datos.rfc);
                        Ext.getCmp('txtRazonSocialPar').setValue(datos.razon_social);
                        Ext.getCmp('txtUsoCFDIPar').setValue(datos.usoCFDI);
                        Ext.getCmp('txtIdDatoFacPar').setValue(datos.id_dato_facturacion);
                    }
                    Ext._id_alumno=datos.id_alumno;
                    Ext.getCmp('id_ciclo_escolarPar').setValue(Ext._id_ciclo_escolar);
                    Ext.getCmp('id_institucionPar').setValue(Ext._id_institucion);
                    //  id_institucion_cobroAnu



                }




                /*  Ext.getStore('CobrosCarnetParcialidadStore').load({
                params:{
                'id_institucion': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar,
                'id_alumno': Ext._id_alumno

                }
                }); */



                Ext.getStore('CobrosCarnetParcialidadStore').load({
                    params:{
                        'id_institucion': Ext._id_institucion,
                        'id_ciclo_escolar': Ext._id_ciclo_escolar,
                        'id_alumno': Ext._id_alumno

                    },

                    callback: function(records) {
                        if (records.length >= 0) {
                            var importe=records[0].data;
                            Ext.getCmp('txtConceptoPar').setValue(importe.concepto);
                            //Ext.getCmp('cmbTipoPar').setValue("INSCRIPC");
                            Ext.getCmp('txtImporteAnu').setValue(importe.cuota);
                            Ext.getCmp('txtDescuentoBecaAnu').setValue(importe.beca);
                            Ext.getCmp('txtTransporteAnu').setValue(importe.transporte);
                            Ext.getCmp('txtSubtotalAnu').setValue(importe.subtotal);
                            Ext.getCmp('txtDescuentoAnu').setValue(importe.descuento);
                            Ext.getCmp('txtSaldoAnu').setValue(importe.importe);

                        }
                    }

                });

            }




        });


        Ext.getCmp('AlumnosParcialidadTab').destroy();
    }

});
