/*
 * File: app/view/InstitucionesTabViewController2.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesTabViewController2', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.rolestab',

    onBtnAgregarInsClick: function(button, e, eOpts) {
        var FormInstituciones = Ext.create('cartera.view.InstitucionesWin');
        FormInstituciones.show();
    },

    onBtnBorrarCicloClick: function(button, e, eOpts) {
        var record = Ext.getCmp('GridInstituciones').getSelectionModel().getSelection()[0];
        if(record !== undefined){
            var estatus = Ext.getCmp('GridInstituciones').getSelectionModel().getSelection()[0].data.estatus;
            var razon_social = Ext.getCmp('GridInstituciones').getSelectionModel().getSelection()[0].data.razon_social;
            console.log(estatus);
            if(estatus === 1){
                Ext.MessageBox.show({
                    title : 'Desactivar Institución',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Desactivar a '+razon_social+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 0};
                            record.set(values);
                            Ext.getStore('DatosStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Institución',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Institución desactivada correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
            else{
                Ext.MessageBox.show({
                    title : 'Activar Institución',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Activar a '+razon_social+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 1};
                            record.set(values);
                            Ext.getStore('DatosStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Activar Institución',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Institución activada correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
        }
        else{
            Ext.MessageBox.show({
                title : 'Información',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.INFO
            });

        }
    },

    onBtnModificarCicloClick: function(button, e, eOpts) {
        records = Ext.getCmp('GridInstituciones').getSelectionModel().getSelection();
        if(records.length > 0){
            var WinInstituciones = Ext.create('cartera.view.InstitucionesWin'),
                EditForm = WinInstituciones.down('form'),
                record = records[0],
                form = Ext.getCmp('institucionesForm');

            WinInstituciones.setTitle('Modificar Institución');
            form.getForm().loadRecord(record);
            Ext.getCmp('institucionescmb').disabled=true;
            var imagen = records[0].data.ruta_logo;
            if (imagen!==""){
                Ext.getCmp('imglogo').setSrc("api/webroot/"+imagen);
            }else{
                Ext.getCmp('imglogo').setSrc("api/webroot/sinfoto.png");
            }

        }else{
            Ext.MessageBox.show({
                title : 'Advertencia',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.ERROR

            });
        }
    },

    onBtnActualizarInsClick: function(button, e, eOpts) {
        Ext.getStore('RolesStore').load({
            params:{
                'id_ins': Ext._id_institucion
            },
        });

    },

    onGridcolumnAfterRender: function(component, eOpts) {
        Ext.getStore('RolesStore').load({
            params:{
                'id_ins': Ext._id_institucion
            },
        });
    }

});
