/*
 * File: app/view/InstitucionesWinViewController13.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesWinViewController13', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.carnetswin2',

    onCmbUsoUCChange: function(field, newValue, oldValue, eOpts) {

        var lengthRecord = field.lastSelectedRecords;
        var id_tipo_movimiento = field.lastSelectedRecords[0].data.id_tipo_movimiento;

        if(lengthRecord !== null){
            Ext.getCmp('id_tipo_movimiento').setValue(id_tipo_movimiento);
            if(id_tipo_movimiento==2){
                Ext.getCmp('rgroupColeg').enable();
            }else{
                Ext.getCmp('rgroupColeg').disable();
            }


        }
    },

    onCmbUsoUCChange1: function(field, newValue, oldValue, eOpts) {


    },

    onCmbUsoUCChange11: function(field, newValue, oldValue, eOpts) {

    },

    onbtnGuardarUC: function(button, e, eOpts) {
        Ext.getCmp('ciclo_escolar').setValue(Ext._id_ciclo_escolar);
        var win = button.up('window'),
            form   = Ext.getCmp('formCarnets'),
            record = form.getRecord(),
            values = form.getValues();


        if(form.isValid()){
            //Agregar Carnet a Todos los Alumnos.
            if(Ext.getCmp('rbtTodos').getValue()===true){
                record = Ext.create('cartera.model.CarnetsModel');
                console.log(record);
                record.set(values);
                form.submit({
                    params: Ext.JSON.encode(values),
                    url: 'api/carnets/createall',
                    waitMsg: 'Procesando información...',
                    success: function() {


                        Ext.MessageBox.show({
                            title : 'Información',
                            buttons : Ext.MessageBox.OK,
                            msg : 'El carnet se ha generado',
                            icon : Ext.Msg.INFO

                        });

                        Ext.getStore('CarnetsStore').load({
                            params:{
                                'id_ins': Ext._id_institucion,
                                'id_ciclo_escolar': Ext._id_ciclo_escolar
                            },
                        });


                        win.close();
                    },
                    failure: function() {
                        //console.log('FAILURE CAPTURA INSTITUCION');
                    }
                });


            }else{

                // Agregar un solo carnet
                if(Ext.getCmp('id_carnet_inscripcionC').getValue() > 0 && Ext.getCmp('id_ciclo_escolarC').getValue() == Ext._id_ciclo_escolar){
                    Ext.MessageBox.show({
                        title : 'Advertencia',
                        buttons : Ext.MessageBox.OK,
                        msg : 'Ya existen datos para ese alumno. Verifique...',
                        icon : Ext.Msg.ERROR
                    });

                }else{


                    record = Ext.create('cartera.model.CarnetsModel');
                    console.log(record);
                    record.set(values);
                    form.submit({
                        params: Ext.JSON.encode(values),
                        url: 'api/carnets/create',
                        waitMsg: 'Procesando información...',
                        success: function() {


                            Ext.MessageBox.show({
                                title : 'Información',
                                buttons : Ext.MessageBox.OK,
                                msg : 'El carnet se ha generado',
                                icon : Ext.Msg.INFO

                            });

                            Ext.getStore('CarnetsStore').load({
                                params:{
                                    'id_ins': Ext._id_institucion,
                                    'id_ciclo_escolar': Ext._id_ciclo_escolar
                                },
                            });


                            win.close();
                        },
                        failure: function() {
                            //console.log('FAILURE CAPTURA INSTITUCION');
                        }
                    });





                }
            }

        }else{
            //Si el formulario no es válido
            Ext.MessageBox.show({
                title : 'Atencion',
                buttons : Ext.MessageBox.OK,
                msg : 'Ingrese todos los campos obligatorios',
                icon : Ext.Msg.ERROR
            });
        }
    },

    onbtnCancelarUC: function(button, e, eOpts) {
        button.up('window').close();
    },

    onUsoCFDIWinAfterRender: function(component, eOpts) {


        Ext.getStore('CarnetsStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar,
                'id_cuota_inscripcion': Ext._id_cuota_inscripcion
            },
        });



    }

});
