/*
 * File: app/view/InstitucionesWinViewController16.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesWinViewController16', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.correocolwin',

    onbtnGuardarCo: function(button, e, eOpts) {
        var id_institucion = Ext._id_institucion;
        var id_ciclo_escolar=Ext._id_ciclo_escolar;
        var id_alumno =records[0].data.id_alumno;
        var id_status_ciclo =records[0].data.id_status_ciclo;
        var grado =records[0].data.grado;
        var id_nivel_educativo=records[0].data.id_nivel_educativo;
        var concepto=records[0].data.concepto;
        var id_carnet_colegiatura=records[0].data.id_carnet_colegiatura;
        var correo =Ext.getCmp('cmbCorreo').getValue();
        var win = button.up('window');



        // ENVIAR EL CARNET DE COLEGIATURA
        new Ext.Window({
            title : "CARNET DE COLEGIATURA",
            width : 990,
            maximizable: true,
            modal: true,
            height: 700,
            layout : 'fit',
            items : [{
                xtype : "component",
                autoEl : {
                    tag : "iframe",
                    src : "pdf/pdf_CarnetColegiaturaEnviar.php?id_institucion="+id_institucion+"&id_ciclo_escolar="+id_ciclo_escolar+"&concepto="+concepto+"&id_carnet_colegiatura="+id_carnet_colegiatura+"&correo="+correo+"&id_alumno="+id_alumno+"&id_status_ciclo="+id_status_ciclo+"&grado="+grado+"&id_nivel_educativo="+id_nivel_educativo

                }
            }]
        }).show();

        Ext.MessageBox.show({
            title : 'Información',
            buttons : Ext.MessageBox.OK,
            msg : 'Se ha enviado el carnet de colegiatura.',
            icon : Ext.Msg.INFO

        });

        win.close();







    },

    onbtnCancelarCo: function(button, e, eOpts) {
        button.up('window').close();
    },

    onCarnetsWinAfterRender: function(component, eOpts) {

        Ext._id_alumno=records[0].data.id_alumno;
        Ext.getStore('CorreoStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar,
                'id_alumno': Ext._id_alumno
            },
        });

        Ext.getStore('cmbTipoMovimientoStore').load({
            params:{
                'id_ins': Ext._id_institucion,
            },
        });


    }

});
