/*
 * File: app/view/InstitucionesTabViewController14.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesTabViewController14', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tiposmovimientostab',

    onBtnAgregarTMClick: function(button, e, eOpts) {
        var FormTiposMovimentos = Ext.create('cartera.view.TiposMovimientosWin');
        FormTiposMovimentos.show();
    },

    onBtnBorrarTMClick: function(button, e, eOpts) {
        var record = Ext.getCmp('GridTiposMovimientos').getSelectionModel().getSelection()[0];
        if(record !== undefined){
            var estatus = Ext.getCmp('GridTiposMovimientos').getSelectionModel().getSelection()[0].data.estatus;
            var movimiento = Ext.getCmp('GridTiposMovimientos').getSelectionModel().getSelection()[0].data.movimiento;

            if(estatus === 1){
                Ext.MessageBox.show({
                    title : 'Desactivar Movimiento',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Desactivar '+movimiento+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 0};
                            record.set(values);
                            Ext.getStore('TiposMovimientosStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Movimientos',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Movimiento Desactivado Correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
            else{
                Ext.MessageBox.show({
                    title : 'Activar Banco',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Activar a '+nombre+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 1};
                            record.set(values);
                            Ext.getStore('BancosStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Activar Banco',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Banco correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
        }
        else{
            Ext.MessageBox.show({
                title : 'Información',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.INFO
            });

        }
    },

    onBtnActualizarTMClick: function(button, e, eOpts) {
        Ext.getStore('TiposMovimientosStore').load({
            params:{
                'id_ins': Ext._id_institucion
            },
        });
    },

    onGridcolumnAfterRender: function(component, eOpts) {
        Ext.getStore('TiposMovimientosStore').load({
            params:{
                'id_ins': Ext._id_institucion
            },
        });
    }

});
