/*
 * File: app/view/InstitucionesTabViewController5.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesTabViewController5', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.cuotascolegiaturatab',

    onBtnAgregarCuoColClick: function(button, e, eOpts) {
        var FormCuoCol = Ext.create('cartera.view.CuotasColegiaturaWin');
        FormCuoCol.show();
    },

    onBtnBorrarCuoColClick: function(button, e, eOpts) {
        var record = Ext.getCmp('GridCuoCol').getSelectionModel().getSelection()[0];
        if(record !== undefined){
            var estatus = Ext.getCmp('GridCuoCol').getSelectionModel().getSelection()[0].data.estatus;
            var descripcion = Ext.getCmp('GridCuoCol').getSelectionModel().getSelection()[0].data.descripcion;
            console.log(estatus);
            if(estatus === 1){
                Ext.MessageBox.show({
                    title : 'Desactivar Cuota',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Desactivar a '+descripcion+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 0};
                            record.set(values);
                            Ext.getStore('CuotasColegiaturaStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Cuota',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Cuota desactivada correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
            else{
                Ext.MessageBox.show({
                    title : 'Activar Cuota',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Activar a '+descripcion+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 1};
                            record.set(values);
                            Ext.getStore('CuotasColegiaturaStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Activar Cuota',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Cuota activada correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
        }
        else{
            Ext.MessageBox.show({
                title : 'Información',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.INFO
            });

        }
    },

    onBtnModificarCuoColClick: function(button, e, eOpts) {
        records = Ext.getCmp('GridCuoCol').getSelectionModel().getSelection();
        if(records.length > 0){
            var WinCuotasInscripcion = Ext.create('cartera.view.CuotasColegiaturaWin'),
                EditForm = WinCuotasInscripcion.down('form'),
                record = records[0],
                form = Ext.getCmp('formCuotaColegiatura');

            WinCuotasInscripcion.setTitle('Modificar Cuotas de Inscripción');
            form.getForm().loadRecord(record);
            //Ext.getCmp('institucionescmb').disabled=true;

        }else{
            Ext.MessageBox.show({
                title : 'Advertencia',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.ERROR

            });
        }
    },

    onBtnActualizarCuoColClick: function(button, e, eOpts) {
        Ext.getStore('CuotasColegiaturaStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar
            },
        });


    },

    onBtnReporteColClick: function(button, e, eOpts) {

        var id_institucion = Ext._id_institucion;
        var id_ciclo_escolar=Ext._id_ciclo_escolar;

        new Ext.Window({
            title : "CUOTAS DE INSCRIPCIÓN Y COLEGIATURA",
            width : 990,
            maximizable: true,
            modal: true,
            height: 700,
            layout : 'fit',
            items : [{
                xtype : "component",
                autoEl : {
                    tag : "iframe",
                    src : "pdf/pdf_Cuotas.php?id_institucion="+id_institucion+"&id_ciclo_escolar="+id_ciclo_escolar

                }
            }]
        }).show();

    },

    onGridcolumnAfterRender: function(component, eOpts) {
        Ext.getStore('CuotasColegiaturaStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar
            },
        });
    }

});
