/*
 * File: app/view/ReferenciasWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.ReferenciasWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.referenciaswin',

    requires: [
        'cartera.view.InstitucionesWinViewModel15',
        'cartera.view.InstitucionesWinViewController15',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'referenciaswin',
    viewModel: {
        type: 'referenciaswin'
    },
    modal: true,
    autoShow: true,
    height: 215,
    id: 'ReferenciasWin',
    itemId: 'ReferenciasWin',
    resizable: false,
    width: 441,
    title: 'Generar Referencias',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            height: 169,
            id: 'formReferencias',
            itemId: 'formReferencias',
            width: 569,
            layout: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_alumnoRef',
                    fieldLabel: 'id_alumno',
                    name: 'id_alumno',
                    hideTrigger: true
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    id: 'matriculaRef',
                    fieldLabel: 'matricula',
                    name: 'matricula'
                },
                {
                    xtype: 'radiogroup',
                    id: 'rgroupGenerarRef',
                    width: 396,
                    fieldLabel: 'Generar por',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'radiofield',
                            id: 'rbtSelecRef',
                            boxLabel: 'Alumno Seleccionado',
                            checked: true
                        },
                        {
                            xtype: 'radiofield',
                            id: 'rbtTodosRef',
                            boxLabel: 'Todos los Alumnos'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 70,
                    width: 900,
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            dock: 'left'
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnGuardarRef',
                            width: 100,
                            icon: 'resources/images/guardar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Guardar',
                            listeners: {
                                click: 'onbtnGuardarRef'
                            }
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnCancelarRef',
                            width: 100,
                            icon: 'resources/images/cancelar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Cancelar',
                            listeners: {
                                click: 'onbtnCancelarRef'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onCarnetsWinAfterRender'
    }

});