/*
 * File: app/view/RolesTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.RolesTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.rolestab',

    requires: [
        'cartera.view.InstitucionesTabViewModel2',
        'cartera.view.InstitucionesTabViewController2',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number'
    ],

    controller: 'rolestab',
    viewModel: {
        type: 'rolestab'
    },
    height: 630,
    id: 'RolesTab',
    itemId: 'RolesTab',
    width: 829,
    layout: 'fit',
    closable: true,
    title: 'Roles de Usuario',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    disabled: true,
                    height: 45,
                    id: 'btnAgregarCiclo1',
                    itemId: 'btnAgregarCiclo',
                    width: 45,
                    icon: 'resources/images/agregar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnAgregarInsClick'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    height: 45,
                    id: 'btnBorrarCiclo1',
                    itemId: 'btnBorrarCiclo',
                    width: 45,
                    icon: 'resources/images/eliminar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnBorrarCicloClick'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    height: 45,
                    id: 'btnModificarCiclo1',
                    itemId: 'btnModificarCiclo',
                    width: 45,
                    icon: 'resources/images/modificar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnModificarCicloClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnActualizarCiclo1',
                    itemId: 'btnActualizarCiclo',
                    width: 45,
                    icon: 'resources/images/actualizar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnActualizarInsClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'GridRoles',
            store: 'RolesStore',
            columns: [
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'id_rol',
                    menuDisabled: true,
                    text: 'Id',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    width: 350,
                    dataIndex: 'rol',
                    text: 'Rol De Usuario'
                }
            ],
            listeners: {
                afterrender: 'onGridcolumnAfterRender'
            }
        }
    ]

});