/*
 * File: app/view/tabCap.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.tabCap', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabCap',

    requires: [
        'cartera.view.tabArtLisViewModel1',
        'cartera.view.tabArtLisViewController1',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.form.field.Number',
        'Ext.grid.plugin.CellEditing'
    ],

    controller: 'tabcap',
    viewModel: {
        type: 'tabcap'
    },
    height: 630,
    id: 'tabCap',
    itemId: 'tabCap',
    width: 829,
    layout: 'fit',
    closable: true,
    title: 'Captura de Conteo Físico',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    height: 50,
                    id: 'btnImpCap',
                    itemId: 'btnImprimir',
                    width: 50,
                    icon: 'resources/images/pdf.png',
                    iconAlign: 'top',
                    scale: 'large'
                },
                {
                    xtype: 'button',
                    height: 50,
                    id: 'btnExcelCap',
                    itemId: 'btnExcelCap',
                    width: 50,
                    icon: 'resources/images/excel.png',
                    iconAlign: 'bottom',
                    scale: 'large'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'GridArticulos',
            store: 'ArticulosStore',
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id_articulo',
                    menuDisabled: true,
                    text: 'id_articulo',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'consec',
                    menuDisabled: true,
                    text: 'Consec',
                    format: '00000'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'gpo_descrip',
                    menuDisabled: true,
                    text: 'Grupo'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'codigob',
                    menuDisabled: true,
                    text: 'Cod. Barra'
                },
                {
                    xtype: 'gridcolumn',
                    width: 400,
                    dataIndex: 'descrip',
                    menuDisabled: true,
                    text: 'Artículo'
                },
                {
                    xtype: 'gridcolumn',
                    menuDisabled: true,
                    text: 'Físico',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            id: 'existencia',
                            align: 'end',
                            dataIndex: 'exi_fis',
                            menuDisabled: true,
                            text: 'Existencia',
                            editor: {
                                xtype: 'numberfield',
                                id: 'txtCapFis',
                                name: 'Fisico',
                                allowBlank: false,
                                enableKeyEvents: true,
                                enforceMaxLength: true,
                                hideTrigger: true,
                                maxLength: 6,
                                allowDecimals: false,
                                allowExponential: false,
                                minValue: 0,
                                listeners: {
                                    focusleave: 'onTxtCapFisFocusleave',
                                    focusenter: 'onTxtCapFisFocusenter'
                                }
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            align: 'end',
                            dataIndex: 'cto_fis',
                            menuDisabled: true,
                            text: 'Costo'
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sta_descrip',
                    menuDisabled: true,
                    text: 'Estatus'
                }
            ],
            listeners: {
                afterrender: 'onGridcolumnAfterRender'
            },
            plugins: [
                {
                    ptype: 'cellediting',
                    clicksToEdit: 1,
                    listeners: {
                        edit: 'onCellEditingEdit',
                        validateedit: 'onCellEditingValidateedit'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onTabCapAfterRender'
    }

});