/*
 * File: app/view/TiposMovimientosTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.TiposMovimientosTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tiposmovimientostab',

    requires: [
        'cartera.view.InstitucionesTabViewModel14',
        'cartera.view.InstitucionesTabViewController14',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action'
    ],

    controller: 'tiposmovimientostab',
    viewModel: {
        type: 'tiposmovimientostab'
    },
    height: 627,
    id: 'TiposMovimientosTab',
    itemId: 'TiposMovimientosTab',
    width: 829,
    layout: 'fit',
    closable: true,
    title: 'Tipos de movimientos',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnAgregarTM',
                    itemId: 'btnAgregarTM',
                    width: 45,
                    icon: 'resources/images/agregar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnAgregarTMClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnBorrarTM',
                    itemId: 'btnBorrarTM',
                    width: 45,
                    icon: 'resources/images/eliminar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnBorrarTMClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnActualizarTM',
                    itemId: 'btnActualizarTM',
                    width: 45,
                    icon: 'resources/images/actualizar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnActualizarTMClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'GridTiposMovimientos',
            store: 'TiposMovimientosStore',
            columns: [
                {
                    xtype: 'numbercolumn',
                    itemId: 'id_tipo_movimiento',
                    width: 153,
                    dataIndex: 'id_tipo_movimiento',
                    menuDisabled: true,
                    text: 'Tipo Movimiento',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    itemId: 'id_institucion',
                    dataIndex: 'id_institucion',
                    menuDisabled: true,
                    text: 'Id_institucion',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'movimiento',
                    width: 150,
                    dataIndex: 'movimiento',
                    menuDisabled: true,
                    text: 'Descripción'
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        this.items[0].icon = record.get('estatus') == 1 ? "resources/images/ok2.png" : "resources/images/eliminar.png";
                        return value;
                    },
                    dataIndex: 'status',
                    text: 'Estatus',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var movimiento = record.data.movimiento;
                                if(record.data.estatus === 1){
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Movimiento',
                                        buttons : Ext.MessageBox.YESNO,
                                        buttonText:{
                                            yes:'Sí',
                                            no:'No',
                                            cancel:'Cancelar'
                                        },
                                        msg : '¿Desea Desactivar a '+movimiento+'?',
                                        icon : Ext.Msg.WARNING,
                                        fn : function(btn)
                                        {
                                            if (btn == 'yes')
                                            {
                                                var values= {'estatus': 0};
                                                record.set(values);
                                                Ext.getStore('TiposMovimientosStore').sync({
                                                    callback: function(records, operation, success)
                                                    {
                                                        Ext.MessageBox.show({
                                                            title : 'Desactivar Movimientos',
                                                            buttons : Ext.MessageBox.OK,
                                                            msg : 'Movimiento desactivado correctamente',
                                                            icon : Ext.Msg.INFO
                                                        });
                                                    }
                                                });

                                            }
                                        }
                                    });
                                }
                                else{
                                    Ext.MessageBox.show({
                                        title : 'Activar Movimientos',
                                        buttons : Ext.MessageBox.YESNO,
                                        buttonText:{
                                            yes:'Sí',
                                            no:'No',
                                            cancel:'Cancelar'
                                        },
                                        msg : '¿Desea Activar a '+movimiento+'?',
                                        icon : Ext.Msg.WARNING,
                                        fn : function(btn)
                                        {
                                            if (btn == 'yes')
                                            {
                                                var values= {'estatus': 1};
                                                record.set(values);
                                                Ext.getStore('UsoCFDIStore').sync({
                                                    callback: function(records, operation, success)
                                                    {
                                                        Ext.MessageBox.show({
                                                            title : 'Activar Movimiento',
                                                            buttons : Ext.MessageBox.OK,
                                                            msg : 'Movimiento activado correctamente',
                                                            icon : Ext.Msg.INFO
                                                        });
                                                    }
                                                });


                                            }
                                        }
                                    });
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onGridcolumnAfterRender'
            }
        }
    ]

});