/*
 * File: app/model/PromocionesInsModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.model.PromocionesInsModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Number',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'id_descuento_inscripcion'
        },
        {
            type: 'int',
            name: 'id_cuota_inscripcion'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'id_estatus_ingreso'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'cuota'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'total'
        },
        {
            type: 'float',
            allowNull: true,
            name: 'descuento'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'descripcion'
        },
        {
            type: 'date',
            allowNull: true,
            name: 'fecha_inicio',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'date',
            allowNull: true,
            name: 'fecha_fin',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'estatus'
        }
    ]
});