/*
 * File: app/view/AlumnosParcialidadTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.AlumnosParcialidadTab', {
    extend: 'Ext.window.Window',
    alias: 'widget.alumnosparcialidadtab',

    requires: [
        'cartera.view.InstitucionesTabViewModel21',
        'cartera.view.InstitucionesTabViewController21',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column'
    ],

    controller: 'alumnosparcialidadtab',
    viewModel: {
        type: 'alumnosparcialidadtab'
    },
    modal: true,
    height: 530,
    id: 'AlumnosParcialidadTab',
    itemId: 'AlumnosParcialidadTab',
    scrollable: 'vertical',
    width: 632,
    layout: 'form',
    title: 'Alumnos',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'textfield',
                    id: 'txtBuscarAlumnoA1',
                    itemId: 'txtBuscarAlumnoA',
                    width: 420,
                    fieldLabel: 'Buscar alumno',
                    listeners: {
                        change: 'onTextfieldChange',
                        keypress: 'onTextfieldKeypress'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'GridAlumnosAnualidad1',
            store: 'BusAlumnoStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    itemId: 'matricula',
                    width: 152,
                    dataIndex: 'matricula_nueva',
                    menuDisabled: true,
                    text: 'Matrícula'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'ap_paterno',
                    width: 150,
                    dataIndex: 'ap_paterno',
                    menuDisabled: true,
                    text: 'Apellido Paterno'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'ap_materno',
                    width: 150,
                    dataIndex: 'ap_materno',
                    menuDisabled: true,
                    text: 'Apellido Materno'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'nombre',
                    width: 277,
                    dataIndex: 'nombre',
                    menuDisabled: true,
                    text: 'Nombre'
                }
            ],
            listeners: {
                afterrender: 'onGridcolumnAfterRender',
                celldblclick: 'onGridAlumosCCellDblClick'
            }
        }
    ]

});