/*
 * File: app/view/AnualidadesWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.AnualidadesWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.anualidadeswin',

    requires: [
        'cartera.view.InstitucionesWinViewModel20',
        'cartera.view.InstitucionesWinViewController20',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer'
    ],

    controller: 'anualidadeswin',
    viewModel: {
        type: 'anualidadeswin'
    },
    modal: true,
    autoShow: true,
    height: 834,
    id: 'winAnualidades',
    itemId: 'winAnualidades',
    resizable: false,
    width: 926,
    title: 'Agregar Anualidad',

    items: [
        {
            xtype: 'form',
            height: 743,
            id: 'AnualidadesForm',
            itemId: 'AnualidadesForm',
            width: 458,
            layout: 'auto',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 220,
                    width: 459,
                    layout: 'auto',
                    title: 'Alumno',
                    items: [
                        {
                            xtype: 'container',
                            dock: 'top',
                            height: 46,
                            width: 428,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    dock: 'bottom',
                                    height: 35,
                                    id: 'txtMatriculaAnu',
                                    width: 369,
                                    fieldLabel: 'Matrícula',
                                    name: 'matricula',
                                    allowBlank: false,
                                    maxLengthText: '',
                                    validateBlank: true,
                                    listeners: {
                                        specialkey: {
                                            fn: 'onTxtMatriculaASpecialkey',
                                            element: ''
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 36,
                                    id: 'btnGuardarCobro3',
                                    margin: '',
                                    width: 54,
                                    arrowAlign: 'bottom',
                                    icon: 'resources/images/search.png',
                                    iconAlign: 'top',
                                    scale: 'large',
                                    tooltip: 'Buscar Alumno',
                                    listeners: {
                                        click: 'onbtnGuardarCobro1'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtAlumnoAnu',
                            width: 421,
                            fieldLabel: 'Alumno',
                            name: 'nombre',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtNivelAnu',
                            fieldLabel: 'Nivel',
                            name: 'nivel',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'container',
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    dock: 'left',
                                    id: 'txtGrupoAnu',
                                    width: 219,
                                    fieldLabel: 'Grupo',
                                    name: 'grupo',
                                    allowBlank: false,
                                    editable: false,
                                    maxLengthText: '',
                                    validateBlank: true
                                },
                                {
                                    xtype: 'textfield',
                                    dock: 'bottom',
                                    id: 'txtGradoAnu',
                                    width: 204,
                                    fieldLabel: 'Grado',
                                    labelAlign: 'right',
                                    name: 'grado',
                                    allowBlank: false,
                                    editable: false,
                                    maxLengthText: '',
                                    validateBlank: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 640,
                    width: 459,
                    title: 'Carnet',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'cmbTipoAnu',
                            width: 419,
                            fieldLabel: 'Tipo Carnet',
                            name: 'rfc',
                            allowBlank: false,
                            editable: false,
                            maxLength: 13,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtReferenciaAnu',
                            width: 419,
                            fieldLabel: 'No. Referencia ',
                            name: 'rfc',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'gridpanel',
                            dock: 'bottom',
                            height: 449,
                            id: 'GridMeses',
                            width: 425,
                            title: '',
                            store: 'MesesAnualidadStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    width: 242,
                                    dataIndex: 'id_carnet_colegiatura',
                                    text: 'id_carnet_colegiatura'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 229,
                                    dataIndex: 'mes',
                                    text: 'Mes '
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 122,
                                    align: 'end',
                                    dataIndex: 'cuota',
                                    text: 'Importe'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'form',
            dock: 'right',
            height: 768,
            id: 'CobroAForm',
            itemId: 'CobroAForm',
            width: 450,
            layout: 'form',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 185,
                    width: 449,
                    layout: 'form',
                    title: 'Datos Facturación',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'cmbRFCAnu',
                            fieldLabel: 'RFC',
                            name: 'rfc',
                            allowBlank: false,
                            editable: false,
                            validateBlank: true,
                            displayField: 'rfc',
                            store: 'cmbRFCStore',
                            valueField: 'rfc',
                            listeners: {
                                change: 'onCmbRFCFChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtRazonSocialAnu',
                            fieldLabel: 'Razón Social',
                            name: 'razon_social',
                            allowBlank: false,
                            editable: false,
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtUsoCFDIAnu',
                            fieldLabel: 'Uso CFDI',
                            name: 'uso_cfdi',
                            allowBlank: false,
                            editable: false,
                            validateBlank: true
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 540,
                    layout: 'form',
                    title: 'Datos del Cobro',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'cmbFormaPagoAnu',
                            fieldLabel: 'Forma de Pago',
                            name: 'id_forma_pago',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true,
                            displayField: 'forma_pago',
                            store: 'cmbFormasPago',
                            valueField: 'id_forma_pago',
                            listeners: {
                                change: 'onCmbFormaPagoAnuChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            alignTarget: 'right',
                            defaultAlign: 'r-r',
                            id: 'txtImporteAnu',
                            style: '',
                            fieldLabel: 'Importe',
                            name: 'cuota',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'id_institucion_anualidad',
                            width: 419,
                            fieldLabel: 'id_institucion',
                            name: 'id_institucion_cobro',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'txtIdDatoFacAnu',
                            fieldLabel: 'id_dato_fac',
                            name: 'id_dato_facturacion',
                            editable: false,
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            id: 'id_facturacion_transporteAnu',
                            width: 419,
                            fieldLabel: 'id_transporte',
                            name: 'id_facturacion_transporte',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'txtId_alumnoAnu',
                            fieldLabel: 'id_alumno',
                            name: 'id_alumno',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtDescuentoBecaAnu',
                            fieldLabel: ' Beca/Promoción',
                            name: 'beca',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtTransporteAnu',
                            width: 105,
                            fieldLabel: '( + ) Transporte',
                            name: 'transporte',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'id_ciclo_anualidad',
                            width: 105,
                            fieldLabel: 'id_ciclo_escolar',
                            name: 'id_ciclo_escolar',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'checkboxfield',
                            dock: 'right',
                            id: 'chckFacturaAnu',
                            fieldLabel: 'Facturar transporte por separado',
                            boxLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtSubtotalAnu',
                            fieldLabel: 'Subtotal',
                            name: 'subtotal',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            id: 'txtDescuentoAnu',
                            style: '',
                            fieldLabel: '( - ) Descuento',
                            name: 'descuento',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true,
                            listeners: {
                                specialkey: 'onTxtDescuentoCoSpecialkey',
                                focusleave: 'onTxtDescuentoCoFocusleave'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            id: 'txtSaldoAnu',
                            style: '',
                            fieldLabel: 'Importe',
                            name: 'importe',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true,
                            minText: '',
                            minValue: 0
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'bottom',
            height: 65,
            width: 914,
            items: [
                {
                    xtype: 'tbspacer',
                    flex: 1,
                    dock: 'left'
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnGuardarCobro1',
                    width: 100,
                    icon: 'resources/images/guardar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    tooltip: 'Guardar',
                    listeners: {
                        click: 'onbtnGuardarCobro'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnCancelarCobro1',
                    width: 100,
                    icon: 'resources/images/cancelar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    tooltip: 'Cancelar',
                    listeners: {
                        click: 'onbtnCancelarCobro'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWinGen1AfterRender'
    }

});