/*
 * File: app/view/AnualidadesTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.AnualidadesTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.anualidadestab',

    requires: [
        'cartera.view.InstitucionesTabViewModel16',
        'cartera.view.InstitucionesTabViewController16',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.TextItem',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action'
    ],

    controller: 'anualidadestab',
    viewModel: {
        type: 'anualidadestab'
    },
    height: 622,
    id: 'AnualidadesTab',
    itemId: 'AnualidadesTab',
    width: 1540,
    closable: true,
    title: 'Anualidades',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            flex: 1,
            id: 'PpalPanel7',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    flex: 1,
                    id: 'CapturaCobrosPanel1',
                    layout: 'fit',
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 45,
                                    id: 'btnAgregarAnualidades',
                                    itemId: 'btnAgregarAnualidades',
                                    width: 45,
                                    icon: 'resources/images/agregar.png',
                                    iconAlign: 'top',
                                    scale: 'large',
                                    tooltip: 'Agregar Anualidades',
                                    listeners: {
                                        click: 'onBtnAgregarAnualidadesClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 45,
                                    id: 'btnBorrarAnualidades',
                                    itemId: 'btnBorrarAnualidades',
                                    width: 45,
                                    icon: 'resources/images/eliminar.png',
                                    iconAlign: 'bottom',
                                    scale: 'large',
                                    tooltip: 'Cancelar Anualidades',
                                    listeners: {
                                        click: 'onBtnBorrarAnualidadesClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 45,
                                    hidden: true,
                                    id: 'btnModificarAnualidades',
                                    itemId: 'btnModificarAnualidades',
                                    width: 45,
                                    icon: 'resources/images/modificar.png',
                                    iconAlign: 'bottom',
                                    scale: 'large',
                                    listeners: {
                                        click: 'onBtnModificarAnualidadesClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 45,
                                    id: 'btnActualizarAnualidades',
                                    itemId: 'btnActualizarCobros',
                                    width: 45,
                                    icon: 'resources/images/actualizar.png',
                                    iconAlign: 'bottom',
                                    scale: 'large',
                                    tooltip: 'Actualizar',
                                    listeners: {
                                        click: 'onBtnActualizarAnualidadesClick'
                                    }
                                },
                                {
                                    xtype: 'tbtext',
                                    dock: 'right',
                                    height: 45,
                                    html: 'Movimientos del día 26 de Noviembre de 2019.',
                                    id: 'txtFechaAnu',
                                    itemId: 'txtFechaAnu',
                                    padding: 15,
                                    resizable: false,
                                    style: 'font-weight:bold;font-size: 11pt;display:inline-block; text-align:right;',
                                    width: 1303,
                                    listeners: {
                                        afterrender: 'onTxtFechaAfterRender'
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'GridAnualidades',
                            store: 'AnualidadStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'id_alumno',
                                    menuDisabled: true,
                                    text: 'id_alumno',
                                    format: '0'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'id_cobro',
                                    menuDisabled: true,
                                    text: 'id_cobro',
                                    format: '0'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 120,
                                    defaultWidth: 120,
                                    align: 'center',
                                    dataIndex: 'referencia',
                                    menuDisabled: true,
                                    text: 'N. Referencia'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 279,
                                    dataIndex: 'nombre',
                                    text: 'Alumno(s)'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 314,
                                    dataIndex: 'concepto',
                                    text: 'Concepto'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 120,
                                    dataIndex: 'nivel',
                                    text: 'Nivel'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 120,
                                    align: 'center',
                                    dataIndex: 'grado',
                                    text: 'Grado'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 170,
                                    align: 'center',
                                    dataIndex: 'importe',
                                    hideable: false,
                                    text: 'Importe'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 170,
                                    dataIndex: 'forma_pago',
                                    hideable: false,
                                    text: 'Num. Parcialialidades'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        this.items[0].icon = record.get('estatus_anualidad') == 1 ? "resources/images/ok2.png" : "resources/images/eliminar.png";
                                        return value;
                                    },
                                    width: 170,
                                    align: 'center',
                                    dataIndex: 'id_estatus_cobro',
                                    hideable: false,
                                    text: 'Estatus',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                var nombre = record.data.nombre;
                                                if(record.data.id_estatus_cobro === 1){
                                                    Ext.MessageBox.show({
                                                        title : 'Desactivar Cobro',
                                                        buttons : Ext.MessageBox.YESNO,
                                                        buttonText:{
                                                            yes:'Sí',
                                                            no:'No',
                                                            cancel:'Cancelar'
                                                        },
                                                        msg : '¿Desea Desactivar a '+nombre+'?',
                                                        icon : Ext.Msg.WARNING,
                                                        fn : function(btn)
                                                        {
                                                            if (btn == 'yes')
                                                            {
                                                                var values= {'id_estatus_cobro': 0};
                                                                record.set(values);
                                                                Ext.getStore('CapturaCobrosStore').sync({
                                                                    callback: function(records, operation, success)
                                                                    {
                                                                        Ext.MessageBox.show({
                                                                            title : 'Desactivar Cobros',
                                                                            buttons : Ext.MessageBox.OK,
                                                                            msg : 'Cobro desactivado correctamente',
                                                                            icon : Ext.Msg.INFO
                                                                        });
                                                                    }
                                                                });

                                                            }
                                                        }
                                                    });
                                                }
                                                else{
                                                    Ext.MessageBox.show({
                                                        title : 'Activar Cobro',
                                                        buttons : Ext.MessageBox.YESNO,
                                                        buttonText:{
                                                            yes:'Sí',
                                                            no:'No',
                                                            cancel:'Cancelar'
                                                        },
                                                        msg : '¿Desea Activar a '+nombre+'?',
                                                        icon : Ext.Msg.WARNING,
                                                        fn : function(btn)
                                                        {
                                                            if (btn == 'yes')
                                                            {
                                                                var values= {'id_estatus_cobro': 1};
                                                                record.set(values);
                                                                Ext.getStore('CapturaCobrosStore').sync({
                                                                    callback: function(records, operation, success)
                                                                    {
                                                                        Ext.MessageBox.show({
                                                                            title : 'Activar Cobro',
                                                                            buttons : Ext.MessageBox.OK,
                                                                            msg : 'Cobro activado correctamente',
                                                                            icon : Ext.Msg.INFO
                                                                        });
                                                                    }
                                                                });


                                                            }
                                                        }
                                                    });
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                afterrender: 'onGridcolumnAfterRender11'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});