/*
 * File: app/view/BancosTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.BancosTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.BancosTab',

    requires: [
        'cartera.view.InstitucionesTabViewModel8',
        'cartera.view.InstitucionesTabViewController8',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action'
    ],

    controller: 'bancostab',
    viewModel: {
        type: 'bancostab'
    },
    height: 637,
    id: 'BancosTab',
    itemId: 'BancosTab',
    width: 829,
    layout: 'fit',
    closable: true,
    title: 'Bancos',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnAgregarB',
                    itemId: 'btnAgregarB',
                    width: 45,
                    icon: 'resources/images/agregar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    tooltip: 'Agregar Banco',
                    listeners: {
                        click: 'onBtnAgregarBClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnBorrarB',
                    itemId: 'btnBorrarB',
                    width: 45,
                    icon: 'resources/images/eliminar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    tooltip: 'Eliminar',
                    listeners: {
                        click: 'onBtnBorrarBClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnModificarB',
                    itemId: 'btnModificarB',
                    width: 45,
                    icon: 'resources/images/modificar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    tooltip: 'Modificar',
                    listeners: {
                        click: 'onBtnModificarBClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnActualizarB',
                    itemId: 'btnActualizarB',
                    width: 45,
                    icon: 'resources/images/actualizar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    tooltip: 'Actualizar',
                    listeners: {
                        click: 'onBtnActualizarBClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'GridBancos',
            store: 'BancosStore',
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    itemId: 'id_banco',
                    dataIndex: 'id_banco',
                    menuDisabled: true,
                    text: 'Id',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'nombre',
                    width: 250,
                    dataIndex: 'nombre',
                    menuDisabled: true,
                    text: 'Nombre'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'afiliacion',
                    width: 150,
                    dataIndex: 'afiliacion',
                    menuDisabled: true,
                    text: 'Afiliación'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'num_cta',
                    width: 150,
                    dataIndex: 'num_cta',
                    menuDisabled: true,
                    text: 'Número de Cuenta'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'cta_CLABE',
                    width: 200,
                    dataIndex: 'cta_CLABE',
                    menuDisabled: true,
                    text: 'Cuenta CLABE'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'contacto',
                    width: 180,
                    dataIndex: 'contacto',
                    menuDisabled: true,
                    text: 'Contacto'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'correo',
                    width: 200,
                    dataIndex: 'correo',
                    menuDisabled: true,
                    text: 'Correo'
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        this.items[0].icon = record.get('estatus') == 1 ? "resources/images/ok2.png" : "resources/images/eliminar.png";
                        return value;
                    },
                    dataIndex: 'estatus',
                    text: 'Estatus',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var nombre = record.data.nombre;
                                if(record.data.estatus === 1){
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Banco',
                                        buttons : Ext.MessageBox.YESNO,
                                        buttonText:{
                                            yes:'Sí',
                                            no:'No',
                                            cancel:'Cancelar'
                                        },
                                        msg : '¿Desea Desactivar a '+nombre+'?',
                                        icon : Ext.Msg.WARNING,
                                        fn : function(btn)
                                        {
                                            if (btn == 'yes')
                                            {
                                                var values= {'estatus': 0};
                                                record.set(values);
                                                Ext.getStore('BancosStore').sync({
                                                    callback: function(records, operation, success)
                                                    {
                                                        Ext.MessageBox.show({
                                                            title : 'Desactivar Bancos',
                                                            buttons : Ext.MessageBox.OK,
                                                            msg : 'Banco desactivado correctamente',
                                                            icon : Ext.Msg.INFO
                                                        });
                                                    }
                                                });

                                            }
                                        }
                                    });
                                }
                                else{
                                    Ext.MessageBox.show({
                                        title : 'Activar Banco',
                                        buttons : Ext.MessageBox.YESNO,
                                        buttonText:{
                                            yes:'Sí',
                                            no:'No',
                                            cancel:'Cancelar'
                                        },
                                        msg : '¿Desea Activar a '+nombre+'?',
                                        icon : Ext.Msg.WARNING,
                                        fn : function(btn)
                                        {
                                            if (btn == 'yes')
                                            {
                                                var values= {'estatus': 1};
                                                record.set(values);
                                                Ext.getStore('BancosStore').sync({
                                                    callback: function(records, operation, success)
                                                    {
                                                        Ext.MessageBox.show({
                                                            title : 'Activar Banco',
                                                            buttons : Ext.MessageBox.OK,
                                                            msg : 'Banco activado correctamente',
                                                            icon : Ext.Msg.INFO
                                                        });
                                                    }
                                                });


                                            }
                                        }
                                    });
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onGridcolumnAfterRender'
            }
        }
    ]

});