/*
 * File: app/view/CorreoColWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.CorreoColWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.correocolwin',

    requires: [
        'cartera.view.InstitucionesWinViewModel16',
        'cartera.view.InstitucionesWinViewController16',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'correocolwin',
    viewModel: {
        type: 'correocolwin'
    },
    modal: true,
    autoShow: true,
    height: 178,
    id: 'CorreoColWin',
    itemId: 'CorreoColWin',
    resizable: false,
    width: 441,
    title: 'Enviar Carnets Colegiatura',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            height: 126,
            id: 'formCorreo',
            itemId: 'formCorreo',
            width: 569,
            layout: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'combobox',
                    id: 'cmbCorreo',
                    width: 421,
                    fieldLabel: 'Correo',
                    name: 'correo',
                    readOnly: false,
                    allowBlank: false,
                    displayField: 'correo',
                    store: 'CorreoStore',
                    valueField: 'correo'
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'txtIdAlumno',
                    fieldLabel: 'id_alumno',
                    name: 'id_alumno',
                    hideTrigger: true
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 70,
                    width: 900,
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            dock: 'left'
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnGuardarCo',
                            width: 100,
                            icon: 'resources/images/enviar_correo.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Enviar',
                            listeners: {
                                click: 'onbtnGuardarCo'
                            }
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnCancelarCo',
                            width: 100,
                            icon: 'resources/images/cancelar_correo.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Cancelar',
                            listeners: {
                                click: 'onbtnCancelarCo'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onCarnetsWinAfterRender'
    }

});