/*
 * File: app/view/CuotasTransporteWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.CuotasTransporteWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.cuotastransportewin',

    requires: [
        'cartera.view.InstitucionesWinViewModel3',
        'cartera.view.InstitucionesWinViewController3',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'cuotastransportewin',
    viewModel: {
        type: 'cuotastransportewin'
    },
    modal: true,
    autoShow: true,
    height: 315,
    id: 'CuotasTransporteWin',
    itemId: 'CuotasTransporteWin',
    resizable: false,
    width: 482,
    title: 'Agregar Cuota de Transporte',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            height: 276,
            id: 'formCuotaTransporte',
            itemId: 'formCuotaTransporte',
            width: 881,
            layout: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_cuota_transporte',
                    fieldLabel: 'id_cuota_transporte',
                    name: 'id_cuota_transporte',
                    hideTrigger: true
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_insCT',
                    fieldLabel: 'id_institucion',
                    name: 'id_institucion',
                    hideTrigger: true
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_ciclo_escolarCT',
                    fieldLabel: 'id_ciclo_escolar',
                    name: 'id_ciclo_escolar',
                    hideTrigger: true
                },
                {
                    xtype: 'textfield',
                    id: 'descripcionCT',
                    fieldLabel: 'Descripcion',
                    name: 'descripcion',
                    allowBlank: false,
                    validateBlank: true,
                    listeners: {
                        change: 'ondescripcionCTChange'
                    }
                },
                {
                    xtype: 'numberfield',
                    id: 'cuotaCT',
                    fieldLabel: 'Cuota',
                    name: 'cuota',
                    hideTrigger: true
                },
                {
                    xtype: 'textareafield',
                    id: 'observacionCT',
                    fieldLabel: 'Observaciones',
                    name: 'observacion',
                    validateBlank: true,
                    listeners: {
                        change: 'onobservacionCTChange'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 84,
                    width: 843,
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            dock: 'left'
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnGuardarCT',
                            width: 100,
                            icon: 'resources/images/guardar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Guardar',
                            listeners: {
                                click: 'onbtnGuardarCT'
                            }
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnCancelarCT',
                            width: 100,
                            icon: 'resources/images/cancelar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Cancelar',
                            listeners: {
                                click: 'onbtnCancelarCT'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onCuotasTransporteWinAfterRender'
    }

});