/*
 * File: app/view/CuotasInscripcionWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.CuotasInscripcionWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.cuotasinscripcionwin',

    requires: [
        'cartera.view.InstitucionesWinViewModel4',
        'cartera.view.InstitucionesWinViewController4',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'cuotasinscripcionwin',
    viewModel: {
        type: 'cuotasinscripcionwin'
    },
    modal: true,
    autoShow: true,
    height: 311,
    id: 'CuotasInscripcionWin',
    itemId: 'CuotasInscripcionWin',
    resizable: false,
    width: 482,
    title: 'Agregar Cuota de Inscripción',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            height: 269,
            id: 'formCuotaInscripcion',
            itemId: 'formCuotaInscripcion',
            width: 881,
            layout: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_cuota_inscripcion',
                    fieldLabel: 'id_cuota_inscripcion',
                    name: 'id_cuota_inscripcion',
                    hideTrigger: true
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_insCI',
                    fieldLabel: 'id_institucion',
                    name: 'id_institucion',
                    hideTrigger: true
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_ciclo_escolar',
                    fieldLabel: 'id_ciclo_escolar',
                    name: 'id_ciclo_escolar',
                    hideTrigger: true
                },
                {
                    xtype: 'combobox',
                    id: 'nivelcmb',
                    fieldLabel: 'Nivel',
                    name: 'id_nivel_educativo',
                    editable: false,
                    displayField: 'nombre',
                    queryMode: 'local',
                    store: 'NivelesEducativosStore',
                    valueField: 'id_nivel_educativo',
                    listeners: {
                        change: 'onNivelcmbChange'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'gradocmb',
                    fieldLabel: 'Grado',
                    name: 'grado',
                    editable: false,
                    displayField: 'grado',
                    queryMode: 'local',
                    store: 'GradosStore',
                    valueField: 'grado'
                },
                {
                    xtype: 'textfield',
                    id: 'descripcion',
                    fieldLabel: 'Descripcion',
                    name: 'descripcion',
                    allowBlank: false,
                    validateBlank: true,
                    listeners: {
                        change: 'ondescripcionChange'
                    }
                },
                {
                    xtype: 'numberfield',
                    id: 'cuota',
                    fieldLabel: 'Cuota',
                    name: 'cuota',
                    hideTrigger: true
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 84,
                    width: 843,
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            dock: 'left'
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnGuardarCi',
                            width: 100,
                            icon: 'resources/images/guardar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Guardar',
                            listeners: {
                                click: 'onbtnGuardarCi'
                            }
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnCancelarCi',
                            width: 100,
                            icon: 'resources/images/cancelar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Cancelar',
                            listeners: {
                                click: 'onbtnCancelarCi'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onCuotasInscripcionWinAfterRender'
    }

});