/*
 * File: app/view/DatosFactTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.DatosFactTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.datosfacttab',

    requires: [
        'cartera.view.InstitucionesTabViewModel9',
        'cartera.view.InstitucionesTabViewController9',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action'
    ],

    controller: 'datosfacttab',
    viewModel: {
        type: 'datosfacttab'
    },
    height: 906,
    id: 'DatosFactTab',
    itemId: 'DatosFactTab',
    width: 829,
    closable: true,
    title: 'Datos de Facturación',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'panel',
            flex: 1,
            layout: 'fit',
            items: [
                {
                    xtype: 'panel',
                    id: 'FamiliasPanel',
                    width: 350,
                    layout: 'fit',
                    title: 'Familias',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 45,
                                    id: 'btnActualizarFamilias',
                                    itemId: 'btnActualizarFamilias',
                                    width: 45,
                                    icon: 'resources/images/actualizar.png',
                                    iconAlign: 'bottom',
                                    scale: 'large',
                                    listeners: {
                                        click: 'onBtnActualizarFamiliasClick'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'txtBusFamilia',
                                    width: 356,
                                    fieldLabel: 'Buscar Familia',
                                    listeners: {
                                        keypress: 'onTextfieldKeypress',
                                        change: 'onTextfieldChange'
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'GridFamilias',
                            store: 'FamiliasFacStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'id_familia',
                                    menuDisabled: true,
                                    text: 'id_familia',
                                    format: '0'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'id_institucion',
                                    menuDisabled: true,
                                    text: 'id_institucion',
                                    format: '0'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 150,
                                    dataIndex: 'ncontrol',
                                    text: 'Núm de Control'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 200,
                                    dataIndex: 'ap_paterno',
                                    text: 'Apellido Paterno'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 200,
                                    dataIndex: 'ap_materno',
                                    text: 'Apellido Materno'
                                }
                            ],
                            listeners: {
                                afterrender: 'onGridcolumnAfterRender',
                                select: 'onGridFamiliasSelect'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            id: 'PpalPanel',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    flex: 1,
                    id: 'DatosFactPanel',
                    layout: 'fit',
                    title: 'Datos Facturación',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 45,
                                    id: 'btnAgregarDatosFact',
                                    itemId: 'btnAgregarDatosFact',
                                    width: 45,
                                    icon: 'resources/images/agregar.png',
                                    iconAlign: 'top',
                                    scale: 'large',
                                    listeners: {
                                        click: 'onBtnAgregarDatosFactClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 45,
                                    id: 'btnBorrarDatosFact',
                                    itemId: 'btnBorrarTutores',
                                    width: 45,
                                    icon: 'resources/images/eliminar.png',
                                    iconAlign: 'bottom',
                                    scale: 'large',
                                    listeners: {
                                        click: 'onBtnBorrarDatosFactClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 45,
                                    id: 'btnModificarDatosFact',
                                    itemId: 'btnModificarDatosFact',
                                    width: 45,
                                    icon: 'resources/images/modificar.png',
                                    iconAlign: 'bottom',
                                    scale: 'large',
                                    listeners: {
                                        click: 'onBtnModificarDatosFactClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 45,
                                    id: 'btnActualizarDatosFact',
                                    itemId: 'btnActualizarDatosFact',
                                    width: 45,
                                    icon: 'resources/images/actualizar.png',
                                    iconAlign: 'bottom',
                                    scale: 'large',
                                    listeners: {
                                        click: 'onBtnActualizarDatosFactClick'
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'GridDatosFact',
                            store: 'DatosFactStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'id_dato_facturacion',
                                    menuDisabled: true,
                                    text: 'id_dato_facturacion',
                                    format: '0'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'id_alumno',
                                    menuDisabled: true,
                                    text: 'id_alumno',
                                    format: '0'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'calle',
                                    text: 'Calle'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'colonia',
                                    text: 'Colonia'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'numero_exterior',
                                    text: 'Número Exterior'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'numero_interior',
                                    text: 'Número Interior'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'codigo_postal',
                                    text: 'Código Postal'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'estado',
                                    text: 'Estado'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'localidad',
                                    text: 'Localidad'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'municipio',
                                    text: 'Municipio'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 170,
                                    dataIndex: 'predeterminado',
                                    text: 'País'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 170,
                                    dataIndex: 'rfc',
                                    text: 'RFC'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 300,
                                    dataIndex: 'razon_social',
                                    text: 'Razón Social'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 125,
                                    align: 'center',
                                    dataIndex: 'usoCFDI',
                                    text: 'Uso CFDI'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        this.items[0].icon = record.get('estatus') == 1 ? "resources/images/ok2.png" : "resources/images/eliminar.png";
                                        return value;
                                    },
                                    width: 125,
                                    align: 'center',
                                    dataIndex: 'estatus',
                                    text: 'Estatus',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {


                                                var rfc = record.data.rfc;
                                                if(record.data.estatus === 1){
                                                    Ext.MessageBox.show({
                                                        title : 'Desactivar Datos Facturación',
                                                        buttons : Ext.MessageBox.YESNO,
                                                        buttonText:{
                                                            yes:'Sí',
                                                            no:'No',
                                                            cancel:'Cancelar'
                                                        },
                                                        msg : '¿Desea Desactivar a '+rfc+'?',
                                                        icon : Ext.Msg.WARNING,
                                                        fn : function(btn)
                                                        {
                                                            if (btn == 'yes')
                                                            {
                                                                var values= {'estatus': 0};
                                                                record.set(values);
                                                                Ext.getStore('DatosFactStore').sync({
                                                                    callback: function(records, operation, success)
                                                                    {
                                                                        Ext.MessageBox.show({
                                                                            title : 'Desactivar Datos Facturación',
                                                                            buttons : Ext.MessageBox.OK,
                                                                            msg : 'Datos desactivados correctamente',
                                                                            icon : Ext.Msg.INFO
                                                                        });
                                                                    }
                                                                });

                                                            }
                                                        }
                                                    });
                                                }
                                                else{
                                                    Ext.MessageBox.show({
                                                        title : 'Activar Datos Facturación',
                                                        buttons : Ext.MessageBox.YESNO,
                                                        buttonText:{
                                                            yes:'Sí',
                                                            no:'No',
                                                            cancel:'Cancelar'
                                                        },
                                                        msg : '¿Desea Activar a '+rfc+'?',
                                                        icon : Ext.Msg.WARNING,
                                                        fn : function(btn)
                                                        {
                                                            if (btn == 'yes')
                                                            {
                                                                var values= {'estatus': 1};
                                                                record.set(values);
                                                                Ext.getStore('DatosFactStore').sync({
                                                                    callback: function(records, operation, success)
                                                                    {
                                                                        Ext.MessageBox.show({
                                                                            title : 'Activar Datos Facturación',
                                                                            buttons : Ext.MessageBox.OK,
                                                                            msg : 'Datos activos correctamente',
                                                                            icon : Ext.Msg.INFO
                                                                        });
                                                                    }
                                                                });


                                                            }
                                                        }
                                                    });
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'actioncolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        this.items[0].icon = record.get('predeterminado') == 1 ? "resources/images/ok2.png" : "resources/images/eliminar.png";
                                        return value;
                                    },
                                    width: 125,
                                    align: 'center',
                                    dataIndex: 'predeterminado',
                                    text: 'Predeterminado',
                                    items: [
                                        {

                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                afterrender: 'onGridcolumnAfterRender111'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});