/*
 * File: app/view/FormasPagoWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.FormasPagoWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.formaspagowin',

    requires: [
        'cartera.view.InstitucionesWinViewModel2',
        'cartera.view.InstitucionesWinViewController2',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'formaspagowin',
    viewModel: {
        type: 'formaspagowin'
    },
    modal: true,
    autoShow: true,
    height: 221,
    id: 'FormasPagoWin',
    itemId: 'FormasPagoWin',
    resizable: false,
    width: 419,
    title: 'Agregar Forma de Pago',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'form',
            dock: 'top',
            height: 182,
            id: 'formFormaPago',
            itemId: 'formFormaPago',
            width: 881,
            layout: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_forma_pago',
                    fieldLabel: 'id_forma_pago',
                    name: 'id_forma_pago',
                    hideTrigger: true
                },
                {
                    xtype: 'numberfield',
                    hidden: true,
                    id: 'id_insFP',
                    fieldLabel: 'id_institucion',
                    name: 'id_institucion',
                    hideTrigger: true
                },
                {
                    xtype: 'combobox',
                    id: 'forma_pago',
                    fieldLabel: 'Forma de Pago',
                    name: 'forma_pago',
                    allowBlank: false,
                    validateBlank: true,
                    displayField: 'forma_pago',
                    store: 'cmbFormasPagoWin',
                    valueField: 'forma_pago',
                    listeners: {
                        change: 'onForma_pagoChange'
                    }
                },
                {
                    xtype: 'textfield',
                    id: 'clave',
                    fieldLabel: 'Clave',
                    name: 'clave',
                    allowBlank: false,
                    editable: false,
                    validateBlank: true,
                    listeners: {
                        change: 'onClaveChange'
                    }
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    id: 'forma_pago_id',
                    fieldLabel: 'id',
                    name: 'id',
                    allowBlank: false,
                    validateBlank: true,
                    listeners: {
                        change: 'onClaveChange1'
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    height: 84,
                    width: 843,
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1,
                            dock: 'left'
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnGuardarFp',
                            width: 100,
                            icon: 'resources/images/guardar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Guardar',
                            listeners: {
                                click: 'onbtnGuardarFp'
                            }
                        },
                        {
                            xtype: 'button',
                            height: 45,
                            id: 'btnCancelarFp',
                            width: 100,
                            icon: 'resources/images/cancelar.png',
                            iconAlign: 'top',
                            scale: 'large',
                            tooltip: 'Cancelar',
                            listeners: {
                                click: 'onbtnCancelar'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onFormasPagoWinAfterRender'
    }

});