/*
 * File: app/view/InstitucionesWinViewController17.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesWinViewController17', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.carnetsinswin',

    onbtnGuardarCI: function(button, e, eOpts) {
        Ext.getCmp('ciclo_escolarCI').setValue(Ext._id_ciclo_escolar);
        var win = button.up('window'),
            form   = Ext.getCmp('formCarnetsIns'),
            record = form.getRecord(),
            values = form.getValues();


        if(form.isValid()){
            //Agregar Carnet a Todos los Alumnos.
            if(Ext.getCmp('rbtTodosCI').getValue()===true){
                record = Ext.create('cartera.model.CarnetsInsModel');
                console.log(record);
                record.set(values);
                form.submit({
                    params: Ext.JSON.encode(values),
                    url: 'api/carnetsins/createall',
                    waitMsg: 'Procesando información...',
                    success: function() {


                        Ext.MessageBox.show({
                            title : 'Información',
                            buttons : Ext.MessageBox.OK,
                            msg : 'El carnet se ha generado',
                            icon : Ext.Msg.INFO

                        });

                        Ext.getStore('CarnetsInsStore').load({
                            params:{
                                'id_ins': Ext._id_institucion,
                                'id_ciclo_escolar': Ext._id_ciclo_escolar
                            },
                        });


                        win.close();
                    },
                    failure: function() {
                        //console.log('FAILURE CAPTURA INSTITUCION');
                    }
                });


            }else{

                // Agregar un solo carnet
                if(Ext.getCmp('id_carnet_inscripcionCI').getValue() > 0 && Ext.getCmp('id_ciclo_escolarCI').getValue() == Ext._id_ciclo_escolar){
                    Ext.MessageBox.show({
                        title : 'Advertencia',
                        buttons : Ext.MessageBox.OK,
                        msg : 'Ya existen datos para ese alumno. Verifique...',
                        icon : Ext.Msg.ERROR
                    });

                }else{


                    record = Ext.create('cartera.model.CarnetsInsModel');
                    console.log(record);
                    record.set(values);
                    form.submit({
                        params: Ext.JSON.encode(values),
                        url: 'api/carnetsins/create',
                        waitMsg: 'Procesando información...',
                        success: function() {


                            Ext.MessageBox.show({
                                title : 'Información',
                                buttons : Ext.MessageBox.OK,
                                msg : 'El carnet se ha generado',
                                icon : Ext.Msg.INFO

                            });

                            Ext.getStore('CarnetsInsStore').load({
                                params:{
                                    'id_ins': Ext._id_institucion,
                                    'id_ciclo_escolar': Ext._id_ciclo_escolar
                                },
                            });


                            win.close();
                        },
                        failure: function() {
                            //console.log('FAILURE CAPTURA INSTITUCION');
                        }
                    });

                }
            }

        }
    },

    onbtnCancelarCI: function(button, e, eOpts) {
        button.up('window').close();
    },

    onCarnetsWinAfterRender: function(component, eOpts) {


        Ext.getStore('CarnetsInsStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar,
                'id_cuota_inscripcion': Ext._id_cuota_inscripcion
            },
        });

        Ext.getStore('cmbTipoMovimientoStore').load({
            params:{
                'id_ins': Ext._id_institucion

            },
        });

        Ext.getStore('cmbMesesCicloStore').load({
            params:{
                'id_ins': Ext._id_institucion

            },
        });



    }

});
