/*
 * File: app/view/InstitucionesTabViewController4.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesTabViewController4', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.cuotasinscripciontab',

    onBtnAgregarCuoInsClick: function(button, e, eOpts) {
        var FormCuoIns = Ext.create('cartera.view.CuotasInscripcionWin');
        FormCuoIns.show();
    },

    onBtnBorrarCuoInsClick: function(button, e, eOpts) {
        var record = Ext.getCmp('GridCuoIns').getSelectionModel().getSelection()[0];
        if(record !== undefined){
            var estatus = Ext.getCmp('GridCuoIns').getSelectionModel().getSelection()[0].data.estatus;
            var descripcion = Ext.getCmp('GridCuoIns').getSelectionModel().getSelection()[0].data.descripcion;
            console.log(estatus);
            if(estatus === 1){
                Ext.MessageBox.show({
                    title : 'Desactivar Cuota',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Desactivar a '+descripcion+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 0};
                            record.set(values);
                            Ext.getStore('CuotasInscripcionStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Cuota',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Cuota desactivada correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
            else{
                Ext.MessageBox.show({
                    title : 'Activar Cuota',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Activar a '+descripcion+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 1};
                            record.set(values);
                            Ext.getStore('CuotasInscripcionStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Activar Cuota',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Cuota activada correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
        }
        else{
            Ext.MessageBox.show({
                title : 'Información',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.INFO
            });

        }
    },

    onBtnModificarCuoInsClick: function(button, e, eOpts) {
        records = Ext.getCmp('GridCuoIns').getSelectionModel().getSelection();
        if(records.length > 0){
            var WinCuotasInscripcion = Ext.create('cartera.view.CuotasInscripcionWin'),
                EditForm = WinCuotasInscripcion.down('form'),
                record = records[0],
                form = Ext.getCmp('formCuotaInscripcion');

            WinCuotasInscripcion.setTitle('Modificar Cuotas de Inscripción');
            form.getForm().loadRecord(record);
            //Ext.getCmp('institucionescmb').disabled=true;

        }else{
            Ext.MessageBox.show({
                title : 'Advertencia',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.ERROR

            });
        }
    },

    onBtnActualizarCuoInsClick: function(button, e, eOpts) {
        Ext.getStore('CuotasInscripcionStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar
            },
        });


    },

    onGridcolumnAfterRender: function(component, eOpts) {
        Ext.getStore('CuotasInscripcionStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar
            },
        });
    },

    onGridCuoInsSelect: function(rowmodel, record, index, eOpts) {
        Ext.getStore('PromocionesInsStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar,
                'id_cuota_inscripcion': record.data.id_cuota_inscripcion
            },
        });
    },

    onBtnAgregarPromoClick: function(button, e, eOpts) {
        // console.log('HANDLER');
        //view.select(record);
        records = Ext.getCmp('GridCuoIns').getSelectionModel().getSelection();
        if(records.length > 0){
            var WinCuotasInscripcion = Ext.create('cartera.view.PromocionesInsWin'),
                EditForm = WinCuotasInscripcion.down('form'),
                record = records[0],
                form = Ext.getCmp('formPromocionesIns');

            WinCuotasInscripcion.setTitle('Agregar Promoción');
            form.getForm().loadRecord(record);
            //Ext.getCmp('institucionescmb').disabled=true;

        }else{
            Ext.MessageBox.show({
                title : 'Advertencia',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.ERROR

            });
        }
    },

    onBtnBorrarPromoClick: function(button, e, eOpts) {
        var record = Ext.getCmp('GridCuoIns').getSelectionModel().getSelection()[0];
        if(record !== undefined){
            var estatus = Ext.getCmp('GridCuoIns').getSelectionModel().getSelection()[0].data.estatus;
            var descripcion = Ext.getCmp('GridCuoIns').getSelectionModel().getSelection()[0].data.descripcion;
            console.log(estatus);
            if(estatus === 1){
                Ext.MessageBox.show({
                    title : 'Desactivar Cuota',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Desactivar a '+descripcion+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 0};
                            record.set(values);
                            Ext.getStore('CuotasInscripcionStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Cuota',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Cuota desactivada correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
            else{
                Ext.MessageBox.show({
                    title : 'Activar Cuota',
                    buttons : Ext.MessageBox.YESNO,
                    buttonText:{
                        yes:'Sí',
                        no:'No',
                        cancel:'Cancelar'
                    },
                    msg : '¿Desea Activar a '+descripcion+'?',
                    icon : Ext.Msg.WARNING,
                    fn : function(btn)
                    {
                        if (btn == 'yes')
                        {
                            var values= {'estatus': 1};
                            record.set(values);
                            Ext.getStore('CuotasInscripcionStore').sync({
                                callback: function(records, operation, success)
                                {
                                    Ext.MessageBox.show({
                                        title : 'Activar Cuota',
                                        buttons : Ext.MessageBox.OK,
                                        msg : 'Cuota activada correctamente',
                                        icon : Ext.Msg.INFO
                                    });
                                }
                            });
                        }
                    }
                });
            }
        }
        else{
            Ext.MessageBox.show({
                title : 'Información',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.INFO
            });

        }
    },

    onBtnModificarPromoClick: function(button, e, eOpts) {
        records = Ext.getCmp('GridPromos').getSelectionModel().getSelection();
        if(records.length > 0){
            var WinCuotasInscripcion = Ext.create('cartera.view.PromocionesInsWin'),
                EditForm = WinCuotasInscripcion.down('form'),
                record = records[0],
                form = Ext.getCmp('formPromocionesIns');

            WinCuotasInscripcion.setTitle('Modificar Promoción');
            form.getForm().loadRecord(record);
            //Ext.getCmp('institucionescmb').disabled=true;

        }else{
            Ext.MessageBox.show({
                title : 'Advertencia',
                buttons : Ext.MessageBox.OK,
                msg : 'Seleccione registro.',
                icon : Ext.Msg.ERROR

            });
        }
    },

    onBtnActualizarPromoClick: function(button, e, eOpts) {
        Ext.getStore('PromocionesInsStore').load();
        /* params:{
        'id_ins': Ext._id_institucion,
        'id_ciclo_escolar': Ext._id_ciclo_escolar
        },*/
        //    );


    },

    onGridcolumnAfterRender1: function(component, eOpts) {
        Ext.getStore('CuotasInscripcionStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar
            },
        });
    }

});
