/*
 * File: app/view/InstitucionesWinViewController19.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.InstitucionesWinViewController19', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.carnetscolwin',

    onRbtTodosMesesChange: function(field, newValue, oldValue, eOpts) {
        Ext.getCmp('cmbMesesCicloCol').enable();
        Ext.getCmp('cmbMesesCicloACol').enable();
    },

    onRbtSelecMesChange: function(field, newValue, oldValue, eOpts) {
        Ext.getCmp('cmbMesesCicloCol').disable();
        Ext.getCmp('cmbMesesCicloACol').disable();
    },

    oncmbMesesCicloChange: function(field, newValue, oldValue, eOpts) {

        var lengthRecord = field.lastSelectedRecords;
        var mes1 = field.lastSelectedRecords[0].data.orden;

        if(lengthRecord !== null){
            Ext.getCmp('orden1').setValue(mes1);
        }
    },

    oncmbMesesCicloAChange: function(field, newValue, oldValue, eOpts) {
        var lengthRecord = field.lastSelectedRecords;
        var mes2 = field.lastSelectedRecords[0].data.orden;

        if(lengthRecord !== null){
            Ext.getCmp('orden2').setValue(mes2);
        }
    },

    onbtnGuardarC: function(button, e, eOpts) {
        Ext.getCmp('ciclo_escolarCol').setValue(Ext._id_ciclo_escolar);
        var win = button.up('window'),
            form   = Ext.getCmp('formCarnetsCol'),
            record = form.getRecord(),
            values = form.getValues();


        if(form.isValid()){

            //AGREGAR COLEGIATURAS
            //Agregar Carnet a Todos los Alumnos.
            if(Ext.getCmp('rbtTodosMesesCol').getValue()===true){
                if(Ext.getCmp('rbtTodosCol').getValue()===true){
                    record = Ext.create('cartera.model.CarnetsColModel');
                    console.log(record);
                    record.set(values);
                    form.submit({
                        params: Ext.JSON.encode(values),
                        url: 'api/carnetscol/createallcol',
                        waitMsg: 'Procesando información...',
                        success: function() {


                            Ext.MessageBox.show({
                                title : 'Información',
                                buttons : Ext.MessageBox.OK,
                                msg : 'El carnet se ha generado',
                                icon : Ext.Msg.INFO

                            });


                            Ext.getStore('CarnetsColStore').load({
                                params:{
                                    'id_alumno': record.data.id_alumno,
                                    'id_institucion': Ext._id_institucion,
                                    'id_ciclo_escolar': Ext._id_ciclo_escolar,

                                }
                            });


                            win.close();
                        },
                        failure: function() {
                            //console.log('FAILURE CAPTURA INSTITUCION');
                        }
                    });


                }else{
                    // AGREGAR CARNET AL ALUMNO SELECCIONADO PARA TODO EL CICLO

                    record = Ext.create('cartera.model.CarnetsColModel');
                    console.log(record);
                    record.set(values);
                    form.submit({
                        params: Ext.JSON.encode(values),
                        url: 'api/carnetscol/create',
                        waitMsg: 'Procesando información...',
                        success: function() {


                            Ext.MessageBox.show({
                                title : 'Información',
                                buttons : Ext.MessageBox.OK,
                                msg : 'El carnet se ha generado',
                                icon : Ext.Msg.INFO

                            });


                            Ext.getStore('CarnetsColStore').load({
                                params:{
                                    'id_alumno': record.data.id_alumno,
                                    'id_institucion': Ext._id_institucion,
                                    'id_ciclo_escolar': Ext._id_ciclo_escolar,

                                }
                            });

                            win.close();
                        },
                        failure: function() {

                        }
                    });


                }

            }else{

                //Agregar Carnet a Todos los Alumnos de los meses seleccionados
                if(Ext.getCmp('rbtTodosCol').getValue()===true){
                    if(Ext.getCmp('mes1').getValue() > Ext.getCmp('mes2').getValue()){
                        Ext.MessageBox.show({
                            title : 'Advertencia',
                            buttons : Ext.MessageBox.OK,
                            msg : 'No se puede generar carnet para los meses seleccionados',
                            icon : Ext.Msg.ERROR
                        });

                    }else{
                        record = Ext.create('cartera.model.CarnetsColModel');

                        record.set(values);
                        form.submit({
                            params: Ext.JSON.encode(values),
                            url: 'api/carnetscol/createcolmesall',
                            waitMsg: 'Procesando información...',
                            success: function() {


                                Ext.MessageBox.show({
                                    title : 'Información',
                                    buttons : Ext.MessageBox.OK,
                                    msg : 'El carnet se ha generado',
                                    icon : Ext.Msg.INFO

                                });


                                Ext.getStore('CarnetsColStore').load({
                                    params:{
                                        'id_alumno': record.data.id_alumno,
                                        'id_institucion': Ext._id_institucion,
                                        'id_ciclo_escolar': Ext._id_ciclo_escolar,

                                    }
                                });

                                win.close();
                            },
                            failure: function() {
                                //console.log('FAILURE CAPTURA INSTITUCION');
                            }
                        });

                    }


                }else{
                    // AGREGAR CARNET AL ALUMNO SELECCIONADO EN EL MES SELECCIONADO

                    if(Ext.getCmp('mes1').getValue() > Ext.getCmp('mes2').getValue()){
                        Ext.MessageBox.show({
                            title : 'Advertencia',
                            buttons : Ext.MessageBox.OK,
                            msg : 'No se puede generar carnet para los meses seleccionados',
                            icon : Ext.Msg.ERROR
                        });

                    }else{
                        record = Ext.create('cartera.model.CarnetsColModel');

                        record.set(values);
                        form.submit({
                            params: Ext.JSON.encode(values),
                            url: 'api/carnetscol/createcolmes',
                            waitMsg: 'Procesando información...',
                            success: function() {


                                Ext.MessageBox.show({
                                    title : 'Información',
                                    buttons : Ext.MessageBox.OK,
                                    msg : 'El carnet se ha generado',
                                    icon : Ext.Msg.INFO

                                });


                                Ext.getStore('CarnetsColStore').load({
                                    params:{
                                        'id_alumno': record.data.id_alumno,
                                        'id_institucion': Ext._id_institucion,
                                        'id_ciclo_escolar': Ext._id_ciclo_escolar,

                                    }
                                });

                                win.close();
                            },
                            failure: function() {
                                //console.log('FAILURE CAPTURA INSTITUCION');
                            }
                        });

                    }



                }
            }

        }



    },

    onbtnCancelarC: function(button, e, eOpts) {
        button.up('window').close();
    },

    onCarnetsWinAfterRender: function(component, eOpts) {


        Ext.getStore('CarnetsAlumnosStore').load({
            params:{
                'id_ins': Ext._id_institucion,
                'id_ciclo_escolar': Ext._id_ciclo_escolar,
                'id_cuota_inscripcion': Ext._id_cuota_inscripcion
            },
        });



        Ext.getStore('cmbMesesCicloStore').load({
            params:{
                'id_ins': Ext._id_institucion

            },
        });



    }

});
