/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.MainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    requires: [
        'cartera.view.MainViewportViewModel',
        'cartera.view.MainViewportViewController',
        'Ext.form.FieldContainer',
        'Ext.toolbar.Spacer',
        'Ext.form.field.ComboBox',
        'Ext.Img',
        'Ext.form.Label',
        'Ext.tab.Panel'
    ],

    controller: 'mainviewport',
    viewModel: {
        type: 'mainviewport'
    },
    id: 'MainView',
    layout: 'border',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 99,
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'fieldcontainer',
                    height: 120,
                    width: 400,
                    layout: 'form',
                    items: [
                        {
                            xtype: 'tbspacer',
                            dock: 'right'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Institución',
                            editable: false,
                            displayField: 'razon_social',
                            store: 'DatosStore',
                            valueField: 'id_institucion',
                            listeners: {
                                change: {
                                    fn: 'onComboboxChange',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'combobox',
                            id: 'cicloCmb',
                            itemId: 'cicloCmb',
                            width: 150,
                            fieldLabel: 'Ciclo Escolar',
                            editable: false,
                            displayField: 'ciclo',
                            queryMode: 'local',
                            store: 'CiclosEscolaresStore',
                            valueField: 'id_ciclo_escolar',
                            listeners: {
                                change: {
                                    fn: 'onCicloCmbChange',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    height: 120,
                    width: 400,
                    layout: 'form'
                },
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    height: 120,
                    width: 137,
                    items: [
                        {
                            xtype: 'image',
                            height: 100,
                            width: 261,
                            src: 'resources/images/siapandes.jpg'
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    flex: 3,
                    layout: 'form'
                },
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    height: 120,
                    width: 400,
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 100,
                            id: 'imgLogoIns',
                            width: 100
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: {
                    fn: 'onPanelAfterRender',
                    scope: 'controller'
                }
            }
        },
        {
            xtype: 'panel',
            region: 'west',
            id: 'PnlEste',
            width: 264,
            layout: 'accordion',
            collapsed: false,
            collapsible: true,
            title: 'Menú Principal',
            titleCollapse: false,
            listeners: {
                afterrender: {
                    fn: 'onPnlEsteAfterRender',
                    scope: 'controller'
                }
            }
        },
        {
            xtype: 'panel',
            region: 'south',
            height: 20,
            bodyStyle: 'background-color: #4da67a;color:#fff;',
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'label',
                    style: 'font-weight:bold;font-size: 10pt; ',
                    listeners: {
                        afterrender: 'onLabelAfterRender'
                    }
                }
            ]
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            border: false,
            id: 'tabPrin'
        }
    ],

    onLabelAfterRender: function(component, eOpts) {


        //component.setText('Usuario: '+Ext._nombre);
    }

});