/*
 * File: app/view/ParcialidadesWin.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.ParcialidadesWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.parcialidadeswin',

    requires: [
        'cartera.view.InstitucionesWinViewModel21',
        'cartera.view.InstitucionesWinViewController21',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.form.field.Checkbox',
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer'
    ],

    controller: 'parcialidadeswin',
    viewModel: {
        type: 'parcialidadeswin'
    },
    modal: true,
    autoShow: true,
    height: 713,
    id: 'winParcialidades',
    itemId: 'winParcialidades',
    resizable: false,
    width: 1031,
    title: 'Agregar Parcialidad',

    items: [
        {
            xtype: 'form',
            height: 682,
            id: 'ParcialidadesForm',
            itemId: 'ParcialidadesForm',
            width: 564,
            layout: 'form',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 228,
                    width: 455,
                    title: 'Alumno',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            dock: 'top',
                            height: 46,
                            width: 435,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    dock: 'bottom',
                                    height: 35,
                                    id: 'txtMatriculaPar',
                                    width: 479,
                                    fieldLabel: 'Matrícula',
                                    name: 'matricula',
                                    allowBlank: false,
                                    maxLengthText: '',
                                    validateBlank: true,
                                    listeners: {
                                        specialkey: {
                                            fn: 'onTxtMatriculaASpecialkey',
                                            element: ''
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 36,
                                    id: 'btnGuardarCobro4',
                                    margin: '',
                                    width: 54,
                                    arrowAlign: 'bottom',
                                    icon: 'resources/images/search.png',
                                    iconAlign: 'top',
                                    scale: 'large',
                                    tooltip: 'Buscar Alumno',
                                    listeners: {
                                        click: 'onbtnGuardarCobro1'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtAlumnoPar',
                            fieldLabel: 'Alumno',
                            name: 'nombre',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtNivelPar',
                            fieldLabel: 'Nivel',
                            name: 'nivel',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    dock: 'left',
                                    id: 'txtGrupoPar',
                                    width: 272,
                                    fieldLabel: 'Grupo',
                                    name: 'grupo',
                                    allowBlank: false,
                                    editable: false,
                                    maxLengthText: '',
                                    validateBlank: true
                                },
                                {
                                    xtype: 'textfield',
                                    dock: 'bottom',
                                    id: 'txtGradoPar',
                                    width: 258,
                                    fieldLabel: 'Grado',
                                    labelAlign: 'right',
                                    name: 'grado',
                                    allowBlank: false,
                                    editable: false,
                                    maxLengthText: '',
                                    validateBlank: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 384,
                    width: 449,
                    title: 'Parcialidades',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            id: 'txtConceptoPar',
                            width: 419,
                            fieldLabel: 'Concepto',
                            name: 'concepto',
                            allowBlank: false,
                            allowOnlyWhitespace: false,
                            autoHideInputMask: false,
                            editable: false,
                            maxLengthText: ''
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            hidden: true,
                            id: 'txtIdDatoFacPar',
                            fieldLabel: 'id_dato_fac',
                            name: 'id_dato_facturacion',
                            editable: false,
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            hidden: true,
                            id: 'id_descuento_inscripcionpar',
                            fieldLabel: 'id_descuento_inscripcionpar',
                            name: 'id_descuento_inscripcion',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            hidden: true,
                            id: 'id_carnet_inscripcionPar',
                            fieldLabel: 'id_carnet_inscripcionPar',
                            name: 'id_carnet_inscripcion',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            hidden: true,
                            id: 'id_alumnoPar',
                            fieldLabel: 'id_alumno',
                            name: 'id_alumno',
                            allowBlank: false,
                            editable: false,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'id_ciclo_escolarPar',
                            width: 105,
                            fieldLabel: 'id_ciclo_escolarPar',
                            name: 'id_ciclo_escolarPar',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            hidden: true,
                            id: 'id_institucionPar',
                            width: 419,
                            fieldLabel: 'id_institucionPar',
                            name: 'id_institucionPar',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            maxLengthText: '',
                            validateBlank: true
                        },
                        {
                            xtype: 'container',
                            dock: 'top',
                            height: 45,
                            width: 516,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    id: 'chckNomina',
                                    fieldLabel: 'Descuento por nómina',
                                    labelWidth: 170,
                                    boxLabel: ''
                                },
                                {
                                    xtype: 'textfield',
                                    dock: 'top',
                                    id: 'txtDescPar',
                                    width: 340,
                                    fieldLabel: 'Descuento',
                                    labelAlign: 'right',
                                    name: 'descuento',
                                    allowBlank: false,
                                    maxLengthText: '',
                                    validateBlank: true,
                                    listeners: {
                                        change: 'onTxtDescParChange'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    dock: 'top',
                                    hidden: true,
                                    id: 'txtNomina',
                                    width: 340,
                                    fieldLabel: 'nomina',
                                    labelAlign: 'right',
                                    name: 'nomina',
                                    allowBlank: false,
                                    maxLengthText: '',
                                    validateBlank: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'top',
                            height: 45,
                            width: 516,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    dock: 'left',
                                    id: 'txtTotalPar',
                                    width: 283,
                                    fieldLabel: 'Total a pagar',
                                    name: 'importe',
                                    allowBlank: false,
                                    editable: false,
                                    hideTrigger: true,
                                    maxLengthText: '',
                                    validateBlank: true,
                                    allowDecimals: false
                                },
                                {
                                    xtype: 'textfield',
                                    dock: 'top',
                                    id: 'txtNumPar',
                                    width: 130,
                                    fieldLabel: 'en',
                                    labelAlign: 'right',
                                    labelWidth: 40,
                                    name: 'numero_parcialidades',
                                    allowBlank: false,
                                    maxLengthText: '',
                                    validateBlank: true,
                                    listeners: {
                                        change: 'onTxtNumParChange'
                                    }
                                },
                                {
                                    xtype: 'label',
                                    dock: 'bottom',
                                    height: 35,
                                    modelValidation: false,
                                    padding: 7,
                                    resizable: false,
                                    style: '\'font-size: 10pt; text-align:center;\'',
                                    width: 98,
                                    text: 'Parcialidades'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margins: '',
                            dock: 'top',
                            height: 42,
                            margin: '',
                            padding: '',
                            width: 542,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    dock: 'left',
                                    id: 'txtNumPagoPar',
                                    width: 281,
                                    fieldLabel: 'Distribuidos en',
                                    name: 'grupo',
                                    allowBlank: false,
                                    editable: false,
                                    maxLengthText: '',
                                    validateBlank: true
                                },
                                {
                                    xtype: 'numberfield',
                                    dock: 'top',
                                    id: 'txtPagoPar',
                                    width: 250,
                                    fieldLabel: 'pagos de',
                                    labelAlign: 'right',
                                    labelWidth: 80,
                                    name: 'parcialidad1',
                                    allowBlank: false,
                                    editable: false,
                                    hideTrigger: true,
                                    maxLengthText: '',
                                    validateBlank: true,
                                    allowDecimals: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margins: '',
                            dock: 'top',
                            height: 53,
                            margin: '',
                            padding: '',
                            width: 516,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    dock: 'left',
                                    id: 'txtNum2Par',
                                    width: 280,
                                    fieldLabel: 'y',
                                    name: 'num_par2',
                                    allowBlank: false,
                                    editable: false,
                                    maxLengthText: '',
                                    validateBlank: true
                                },
                                {
                                    xtype: 'numberfield',
                                    dock: 'top',
                                    id: 'txtPago2Par',
                                    width: 250,
                                    fieldLabel: 'parcialidad2',
                                    labelAlign: 'right',
                                    labelWidth: 80,
                                    name: 'parcialidad2',
                                    allowBlank: false,
                                    editable: false,
                                    hideTrigger: true,
                                    maxLengthText: '',
                                    validateBlank: true,
                                    allowDecimals: false
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'form',
            dock: 'right',
            height: 674,
            id: 'CobroAForm1',
            itemId: 'CobroAForm',
            width: 450,
            layout: 'form',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 228,
                    width: 449,
                    layout: 'form',
                    title: 'Datos Facturación',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'cmbRFCPar',
                            fieldLabel: 'RFC',
                            name: 'rfc',
                            allowBlank: false,
                            editable: false,
                            validateBlank: true,
                            displayField: 'rfc',
                            store: 'cmbRFCStore',
                            valueField: 'rfc',
                            listeners: {
                                change: 'onCmbRFCFChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtRazonSocialPar',
                            fieldLabel: 'Razón Social',
                            name: 'razon_social',
                            allowBlank: false,
                            editable: false,
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtUsoCFDIPar',
                            fieldLabel: 'Uso CFDI',
                            name: 'uso_cfdi',
                            allowBlank: false,
                            editable: false,
                            validateBlank: true
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 282,
                    width: 449,
                    layout: 'form',
                    title: 'Datos del Cobro',
                    items: [
                        {
                            xtype: 'textfield',
                            alignTarget: 'right',
                            defaultAlign: 'r-r',
                            id: 'txtImportePar',
                            style: '',
                            fieldLabel: 'Importe',
                            name: 'cuota',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtDescuentoPromPar',
                            fieldLabel: 'Promoción',
                            name: 'beca',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'textfield',
                            id: 'txtSubtotalPar',
                            fieldLabel: 'Subtotal',
                            name: 'subtotal',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true
                        },
                        {
                            xtype: 'numberfield',
                            id: 'txtDescuentoPar',
                            style: '',
                            fieldLabel: '( - ) Descuento',
                            name: 'descuento2',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true,
                            listeners: {
                                specialkey: 'onTxtDescuentoCoSpecialkey',
                                focusleave: 'onTxtDescuentoCoFocusleave'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            id: 'txtSaldoPar',
                            style: '',
                            fieldLabel: 'Importe',
                            name: 'importe',
                            fieldStyle: 'text-align: right',
                            allowBlank: false,
                            editable: false,
                            hideTrigger: true,
                            validateBlank: true,
                            minText: '',
                            minValue: 0
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'bottom',
            height: 65,
            items: [
                {
                    xtype: 'tbspacer',
                    flex: 1,
                    dock: 'left'
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnGuardarParcialidad',
                    width: 100,
                    icon: 'resources/images/guardar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    tooltip: 'Guardar',
                    listeners: {
                        click: 'onbtnGuardarParcialidad'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnCancelarCobro2',
                    width: 100,
                    icon: 'resources/images/cancelar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    tooltip: 'Cancelar',
                    listeners: {
                        click: 'onbtnCancelarCobro'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWinGen1AfterRender'
    }

});