/*
 * File: app/view/tabAjuste.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.tabAjuste', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabAjuste',

    requires: [
        'cartera.view.tabAjusteViewModel',
        'cartera.view.tabAjusteViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.feature.Summary'
    ],

    controller: 'tabajuste',
    viewModel: {
        type: 'tabajuste'
    },
    id: 'tabAjuste',
    itemId: 'tabAjuste',
    layout: 'fit',
    closable: true,
    title: 'Ajustes por Auditoria',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    height: 50,
                    id: 'btnOkAjuste',
                    itemId: 'btnCancelAjuste',
                    width: 50,
                    icon: 'resources/images/ok2.png',
                    iconAlign: 'top',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnOkAjusteClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 50,
                    id: 'btnCancelAjuste',
                    itemId: 'btnExcel',
                    width: 50,
                    icon: 'resources/images/close2.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnCancelAjusteClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'panel',
            id: 'pnlPrincipal',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    flex: 1,
                    id: 'pnlFaltantes',
                    maxWidth: 850,
                    title: 'FALTANTES',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            id: 'GridFaltantes',
                            store: 'FaltantesStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'id_articulo',
                                    menuDisabled: true,
                                    text: 'id_articulo',
                                    format: '0'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 70,
                                    dataIndex: 'consec',
                                    menuDisabled: true,
                                    text: 'Consec',
                                    format: '000000'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'gpo_descrip',
                                    menuDisabled: true,
                                    text: 'Grupo'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'codigob',
                                    menuDisabled: true,
                                    text: 'Cod. Barra'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'descrip',
                                    menuDisabled: true,
                                    text: 'Artículo'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    menuDisabled: true,
                                    text: 'Faltante',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            summaryType: 'sum',
                                            align: 'end',
                                            dataIndex: 'faltante_exi',
                                            menuDisabled: true,
                                            text: 'Existencia'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            summaryType: 'sum',
                                            align: 'end',
                                            dataIndex: 'faltante_cto',
                                            menuDisabled: true,
                                            text: 'Costo'
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                afterrender: 'onGridFaltantesAfterRender'
                            },
                            features: [
                                {
                                    ftype: 'summary',
                                    dock: 'bottom'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    id: 'pnlSobrantes',
                    maxWidth: 850,
                    title: 'SOBRANTES',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            id: 'GridSobrantes',
                            store: 'SobrantesStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'id_articulo',
                                    menuDisabled: true,
                                    text: 'id_articulo',
                                    format: '0'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 70,
                                    dataIndex: 'consec',
                                    menuDisabled: true,
                                    text: 'Consec',
                                    format: '000000'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'gpo_descrip',
                                    menuDisabled: true,
                                    text: 'Grupo'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 170,
                                    dataIndex: 'codigob',
                                    menuDisabled: true,
                                    text: 'Cod. Barra'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'descrip',
                                    menuDisabled: true,
                                    text: 'Artículo'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    menuDisabled: true,
                                    text: 'Sobrante',
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            summaryType: 'sum',
                                            align: 'end',
                                            dataIndex: 'sobrante_exi',
                                            menuDisabled: true,
                                            text: 'Existencia'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            summaryType: 'sum',
                                            align: 'end',
                                            dataIndex: 'sobrante_cto',
                                            menuDisabled: true,
                                            text: 'Costo'
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                afterrender: 'onGridSobrantesAfterRender'
                            },
                            features: [
                                {
                                    ftype: 'summary',
                                    dock: 'bottom'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforeshow: 'onTabAjusteBeforeShow',
        afterrender: 'onTabAjusteAfterRender'
    }

});