/*
 * File: app/view/UsoCFDITab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.UsoCFDITab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.usocfditab',

    requires: [
        'cartera.view.InstitucionesTabViewModel12',
        'cartera.view.InstitucionesTabViewController12',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Action'
    ],

    controller: 'usocfditab',
    viewModel: {
        type: 'usocfditab'
    },
    height: 627,
    id: 'UsoCFDITab',
    itemId: 'UsoCFDITab',
    width: 829,
    layout: 'fit',
    closable: true,
    title: 'Uso CFDI',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnAgregarUC',
                    itemId: 'btnAgregarUC',
                    width: 45,
                    icon: 'resources/images/agregar.png',
                    iconAlign: 'top',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnAgregarUCClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnBorrarUC',
                    itemId: 'btnBorrarUC',
                    width: 45,
                    icon: 'resources/images/eliminar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnBorrarUCClick'
                    }
                },
                {
                    xtype: 'button',
                    height: 45,
                    id: 'btnActualizarUC',
                    itemId: 'btnActualizarUC',
                    width: 45,
                    icon: 'resources/images/actualizar.png',
                    iconAlign: 'bottom',
                    scale: 'large',
                    listeners: {
                        click: 'onBtnActualizarUCClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            id: 'GridUsoCFDI',
            store: 'UsoCFDIStore',
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    itemId: 'id_uso_cfdi',
                    dataIndex: 'id_uso_cfdi',
                    menuDisabled: true,
                    text: 'Id_uso_cfdi',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    itemId: 'id_institucion',
                    dataIndex: 'id_institucion',
                    menuDisabled: true,
                    text: 'Id_institucion',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'clave',
                    width: 150,
                    dataIndex: 'clave',
                    menuDisabled: true,
                    text: 'Clave'
                },
                {
                    xtype: 'gridcolumn',
                    itemId: 'uso',
                    width: 300,
                    dataIndex: 'uso',
                    menuDisabled: true,
                    text: 'Uso CFDI'
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        this.items[0].icon = record.get('status') == 1 ? "resources/images/ok2.png" : "resources/images/eliminar.png";
                        return value;
                    },
                    dataIndex: 'status',
                    text: 'Estatus',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                console.log(record.data.estatus);
                                var uso = record.data.uso;
                                if(record.data.status === 1){
                                    Ext.MessageBox.show({
                                        title : 'Desactivar Uso CFDI',
                                        buttons : Ext.MessageBox.YESNO,
                                        buttonText:{
                                            yes:'Sí',
                                            no:'No',
                                            cancel:'Cancelar'
                                        },
                                        msg : '¿Desea Desactivar a '+uso+'?',
                                        icon : Ext.Msg.WARNING,
                                        fn : function(btn)
                                        {
                                            if (btn == 'yes')
                                            {
                                                var values= {'status': 0};
                                                record.set(values);
                                                Ext.getStore('UsoCFDIStore').sync({
                                                    callback: function(records, operation, success)
                                                    {
                                                        Ext.MessageBox.show({
                                                            title : 'Desactivar Uso CFDI',
                                                            buttons : Ext.MessageBox.OK,
                                                            msg : 'Uso CFDI desactivado correctamente',
                                                            icon : Ext.Msg.INFO
                                                        });
                                                    }
                                                });

                                            }
                                        }
                                    });
                                }
                                else{
                                    Ext.MessageBox.show({
                                        title : 'Activar Uso CFDI',
                                        buttons : Ext.MessageBox.YESNO,
                                        buttonText:{
                                            yes:'Sí',
                                            no:'No',
                                            cancel:'Cancelar'
                                        },
                                        msg : '¿Desea Activar a '+uso+'?',
                                        icon : Ext.Msg.WARNING,
                                        fn : function(btn)
                                        {
                                            if (btn == 'yes')
                                            {
                                                var values= {'status': 1};
                                                record.set(values);
                                                Ext.getStore('UsoCFDIStore').sync({
                                                    callback: function(records, operation, success)
                                                    {
                                                        Ext.MessageBox.show({
                                                            title : 'Activar Uso CFDI',
                                                            buttons : Ext.MessageBox.OK,
                                                            msg : 'Uso CFDI activado correctamente',
                                                            icon : Ext.Msg.INFO
                                                        });
                                                    }
                                                });


                                            }
                                        }
                                    });
                                }
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onGridcolumnAfterRender'
            }
        }
    ]

});