/*
 * File: app/view/windowGenerar.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.view.windowGenerar', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowGenerar',

    requires: [
        'cartera.view.windowGenerarViewModel',
        'cartera.view.windowGenerarViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.ProgressBar',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'windowgenerar',
    viewModel: {
        type: 'windowgenerar'
    },
    modal: true,
    autoShow: true,
    height: 277,
    id: 'winGen',
    itemId: 'winGen',
    resizable: false,
    width: 349,
    title: 'Generar Archivo para Inventario Físico',

    items: [
        {
            xtype: 'form',
            itemId: 'formGenArch',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'fecha',
                    fieldLabel: 'Fecha',
                    name: 'fecha',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    id: 'fisico',
                    fieldLabel: 'Archivo Fisico',
                    name: 'fisico',
                    readOnly: true
                },
                {
                    xtype: 'radiogroup',
                    fieldLabel: 'Items',
                    items: [
                        {
                            xtype: 'radiofield',
                            id: 'exis',
                            value: 1,
                            boxLabel: 'Existencia',
                            checked: true
                        },
                        {
                            xtype: 'radiofield',
                            id: 'todos',
                            value: 2,
                            boxLabel: 'Todos',
                            checked: true
                        }
                    ]
                },
                {
                    xtype: 'progressbar',
                    id: 'proBar'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            height: 32,
                            width: 160,
                            icon: 'resources/images/ok.png',
                            listeners: {
                                click: 'onbtnGuardar'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnCancelar',
                            width: 160,
                            icon: 'resources/images/cancel.png',
                            listeners: {
                                click: 'onbtnCancelar'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onFormGenArchAfterRender'
            }
        }
    ]

});