/*
 * File: app/model/DatosFactModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cartera.model.DatosFactModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'id_datos_facturacion'
        },
        {
            type: 'int',
            name: 'id_alumno'
        },
        {
            type: 'int',
            name: 'estatus'
        },
        {
            type: 'int',
            name: 'usuario_alta'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'rfc'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'razon_social'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'calle'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'colonia'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'numero_exterior'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'numero_interior'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'codigo_postal'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'estado'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'localidad'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'municipio'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'pais'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'predeterminado'
        }
    ]
});